### ISSUE TITLE
请问如何修改文章宽度

### ISSUE THREAD

**Issue by willisfusu** [hsxyhao/gridea-theme-next#1]
你好，请问如何修改文章宽度。在gridea中设置内容区最大宽度，并不起效。感谢。

**Comment by hsxyhao** [comment]
> 你好，请问如何修改文章宽度。在gridea中设置内容区最大宽度，并不起效。感谢。

目前自定义主题配置还不支持，后期会陆续跟进，可以稍晚些时间体验，感谢支持！
