### ISSUE TITLE
“分类”功能跳转

### ISSUE THREAD

**Issue by lyzxh** [hsxyhao/gridea-theme-next#10]
非常感谢作者的贡献！真的很喜欢NEXT这种简约的主题了！
目前的分类功能跳转的是“标签”，请问怎么修复呢？
另外蹲一下多语言版本！
P.S 作者有打赏链接吗~给您爱的催促哈哈

**Comment by hsxyhao** [comment]
> 非常感谢作者的贡献！真的很喜欢NEXT这种简约的主题了！
> 目前的分类功能跳转的是“标签”，请问怎么修复呢？
> 另外蹲一下多语言版本！
> P.S 作者有打赏链接吗~给您爱的催促哈哈

目前的分类跳转的确实是标签，这个主要是受限于gridea平台，暂时不支持分类，当时这样设计的时候也有些犹豫，后期等gridea的更新 ，看会不会支持分类功能。现阶段主题还未发布稳定版本，start就很棒了，后期发布稳定版本后或许会开，如果有什么反馈或者bug欢迎反馈，感谢支持！
