### ISSUE TITLE
请问怎么修改分割线的样式？

### ISSUE THREAD

**Issue by moonaileen** [hsxyhao/gridea-theme-next#101]
我自己修改好了标题的样式，但是标题下面的黑色分割线去不掉，不知道是应该修改哪里？orz
![Snipaste_2020-05-17_22-23-19](https://user-images.githubusercontent.com/2804132/82148077-1e09f080-988d-11ea-8a66-0c4337a7110c.png)

另外还有单独的分割线我也尝试修改了一下，但是在自定义css里修改.next-md-body hr的话，灰色的部分怎么也去不掉，是我修改的方式不对吗😅
![Snipaste_2020-05-17_22-23-47](https://user-images.githubusercontent.com/2804132/82148112-54e00680-988d-11ea-9337-63614f72552b.png)

我有尝试过用图片来当分割线，这个测试倒是可以去掉灰色的部分，但是只要开了cdn的话路径就会变得很奇怪，关上cdn才正常

**Comment by hsxyhao** [comment]
> 我自己修改好了标题的样式，但是标题下面的黑色分割线去不掉，不知道是应该修改哪里？orz
> ![Snipaste_2020-05-17_22-23-19](https://user-images.githubusercontent.com/2804132/82148077-1e09f080-988d-11ea-8a66-0c4337a7110c.png)
> 
> 另外还有单独的分割线我也尝试修改了一下，但是在自定义css里修改.next-md-body hr的话，灰色的部分怎么也去不掉，是我修改的方式不对吗😅
> ![Snipaste_2020-05-17_22-23-47](https://user-images.githubusercontent.com/2804132/82148112-54e00680-988d-11ea-9337-63614f72552b.png)
> 
> 我有尝试过用图片来当分割线，这个测试倒是可以去掉灰色的部分，但是只要开了cdn的话路径就会变得很奇怪，关上cdn才正常

![image](https://user-images.githubusercontent.com/22101306/82167354-19295900-98ee-11ea-8bc1-7c4a9e6b129f.png)
这里可以修改

**Comment by moonaileen** [comment]
> > 我自己修改好了标题的样式，但是标题下面的黑色分割线去不掉，不知道是应该修改哪里？orz
> > ![Snipaste_2020-05-17_22-23-19](https://user-images.githubusercontent.com/2804132/82148077-1e09f080-988d-11ea-8a66-0c4337a7110c.png)
> > 另外还有单独的分割线我也尝试修改了一下，但是在自定义css里修改.next-md-body hr的话，灰色的部分怎么也去不掉，是我修改的方式不对吗😅
> > ![Snipaste_2020-05-17_22-23-47](https://user-images.githubusercontent.com/2804132/82148112-54e00680-988d-11ea-9337-63614f72552b.png)
> > 我有尝试过用图片来当分割线，这个测试倒是可以去掉灰色的部分，但是只要开了cdn的话路径就会变得很奇怪，关上cdn才正常
> 
> ![image](https://user-images.githubusercontent.com/22101306/82167354-19295900-98ee-11ea-8bc1-7c4a9e6b129f.png)
> 这里可以修改

请问是直接修改原始主题文件么？（删掉这部分？）
还是也可以在自定义css里修改呢？

**Comment by hsxyhao** [comment]
> > > 我自己修改好了标题的样式，但是标题下面的黑色分割线去不掉，不知道是应该修改哪里？orz
> > > ![Snipaste_2020-05-17_22-23-19](https://user-images.githubusercontent.com/2804132/82148077-1e09f080-988d-11ea-8a66-0c4337a7110c.png)
> > > 另外还有单独的分割线我也尝试修改了一下，但是在自定义css里修改.next-md-body hr的话，灰色的部分怎么也去不掉，是我修改的方式不对吗😅
> > > ![Snipaste_2020-05-17_22-23-47](https://user-images.githubusercontent.com/2804132/82148112-54e00680-988d-11ea-9337-63614f72552b.png)
> > > 我有尝试过用图片来当分割线，这个测试倒是可以去掉灰色的部分，但是只要开了cdn的话路径就会变得很奇怪，关上cdn才正常
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/22101306/82167354-19295900-98ee-11ea-8bc1-7c4a9e6b129f.png)
> > 这里可以修改
> 
> 请问是直接修改原始主题文件么？（删掉这部分？）
> 还是也可以在自定义css里修改呢？

都可以，不过建议自定义，方便后期更新维护，border-bottom: none !important 大概这样就行了吧

**Comment by moonaileen** [comment]
> > > > 我自己修改好了标题的样式，但是标题下面的黑色分割线去不掉，不知道是应该修改哪里？orz
> > > > ![Snipaste_2020-05-17_22-23-19](https://user-images.githubusercontent.com/2804132/82148077-1e09f080-988d-11ea-8a66-0c4337a7110c.png)
> > > > 另外还有单独的分割线我也尝试修改了一下，但是在自定义css里修改.next-md-body hr的话，灰色的部分怎么也去不掉，是我修改的方式不对吗😅
> > > > ![Snipaste_2020-05-17_22-23-47](https://user-images.githubusercontent.com/2804132/82148112-54e00680-988d-11ea-9337-63614f72552b.png)
> > > > 我有尝试过用图片来当分割线，这个测试倒是可以去掉灰色的部分，但是只要开了cdn的话路径就会变得很奇怪，关上cdn才正常
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/22101306/82167354-19295900-98ee-11ea-8bc1-7c4a9e6b129f.png)
> > > 这里可以修改
> > 
> > 
> > 请问是直接修改原始主题文件么？（删掉这部分？）
> > 还是也可以在自定义css里修改呢？
> 
> 都可以，不过建议自定义，方便后期更新维护，border-bottom: none !important 大概这样就行了吧

谢谢！试了一下黑线去掉了！^0^

那么请问一下普通分割线要怎么修改呢？
我现在在自定义css里是这么设的
``.next-md-body hr {``
``  height: 4px;``
``  background: url(/media/images/line02.png) repeat-x 0 0;``
``}``
但是这样开启cdn的话路径就不对了，只有不开cdn的时候才能正常显示。

**Comment by hsxyhao** [comment]
> > > > > 我自己修改好了标题的样式，但是标题下面的黑色分割线去不掉，不知道是应该修改哪里？orz
> > > > > ![Snipaste_2020-05-17_22-23-19](https://user-images.githubusercontent.com/2804132/82148077-1e09f080-988d-11ea-8a66-0c4337a7110c.png)
> > > > > 另外还有单独的分割线我也尝试修改了一下，但是在自定义css里修改.next-md-body hr的话，灰色的部分怎么也去不掉，是我修改的方式不对吗😅
> > > > > ![Snipaste_2020-05-17_22-23-47](https://user-images.githubusercontent.com/2804132/82148112-54e00680-988d-11ea-9337-63614f72552b.png)
> > > > > 我有尝试过用图片来当分割线，这个测试倒是可以去掉灰色的部分，但是只要开了cdn的话路径就会变得很奇怪，关上cdn才正常
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/22101306/82167354-19295900-98ee-11ea-8bc1-7c4a9e6b129f.png)
> > > > 这里可以修改
> > > 
> > > 
> > > 请问是直接修改原始主题文件么？（删掉这部分？）
> > > 还是也可以在自定义css里修改呢？
> > 
> > 
> > 都可以，不过建议自定义，方便后期更新维护，border-bottom: none !important 大概这样就行了吧
> 
> 谢谢！试了一下黑线去掉了！^0^
> 
> 那么请问一下普通分割线要怎么修改呢？
> 我现在在自定义css里是这么设的
> `.next-md-body hr {`
> ` height: 4px;`
> ` background: url(/media/images/line02.png) repeat-x 0 0;`
> `}`
> 但是这样开启cdn的话路径就不对了，只有不开cdn的时候才能正常显示。

也有可能是cdn没有更新

**Comment by moonaileen** [comment]
不是的，/media/images/line02.png这么设的话，开cdn路径会变成https://cdn.jsdelivr.net/media/images/custom-bgImg2.jpg ，显示不出来
我现在改成了完整外链地址后可以用了，就先这样吧><
