### ISSUE TITLE
更新了主题文件后无法进行预览

### ISSUE THREAD

**Issue by moonaileen** [hsxyhao/gridea-theme-next#103]
点击预览后会显示错误
<img width="1045" alt="Snipaste_2020-05-20_15-56-15" src="https://user-images.githubusercontent.com/2804132/82420874-e4b2ca00-9ab2-11ea-9777-e0a931ab95fe.png">
我没有改过的主题文件，只修改过自定义css。昨晚clone了一下主题文件覆盖了原主题文件后，想预览主题就弹出了上面的错误提示。

**Comment by hsxyhao** [comment]
> 点击预览后会显示错误
> <img alt="Snipaste_2020-05-20_15-56-15" width="1045" src="https://user-images.githubusercontent.com/2804132/82420874-e4b2ca00-9ab2-11ea-9777-e0a931ab95fe.png">
> 我没有改过的主题文件，只修改过自定义css。昨晚clone了一下主题文件覆盖了原主题文件后，想预览主题就弹出了上面的错误提示。

更新的bug，现在试试呢

**Comment by moonaileen** [comment]
可以预览了，但是预览后主题变得特别奇怪，背景看不到了，meta也跟菜单挤在了一起。。。
<img width="310" alt="Snipaste_2020-05-20_16-27-10" src="https://user-images.githubusercontent.com/2804132/82423737-c949be00-9ab6-11ea-96e5-9f8a8ebe5c7a.png">
我把代码改回最早的就可以正常预览了。预览效果也是正常的。
