### ISSUE TITLE
Cannot read property 'startsWith' of undefined

### ISSUE THREAD

**Issue by chenimin** [hsxyhao/gridea-theme-next#105]
点击预览出现报错.
![image.png](https://i.loli.net/2020/05/26/kUfXQl3zWneEHVv.png)

**Comment by hsxyhao** [comment]
> 点击预览出现报错.
> ![image.png](https://camo.githubusercontent.com/9c13ec5040f81b0484412bdfc94b831088b3ee0c/68747470733a2f2f692e6c6f6c692e6e65742f323032302f30352f32362f6b556658516c337a576e65454856762e706e67)

1. 尝试保存下自定义配置
2. 或者上传一张背景图片
3. 加群(734633156)可以快速帮你解决问题
