### ISSUE TITLE
博客可视区宽度调整不起作用！

### ISSUE THREAD

**Issue by chwl66** [hsxyhao/gridea-theme-next#107]
我调整了博客可视区宽度，不管是调大还是调小都不起作用，都是默认宽度！换了几个外观，可视区大小都是默认的没变化！

**Comment by hsxyhao** [comment]
> 我调整了博客可视区宽度，不管是调大还是调小都不起作用，都是默认宽度！换了几个外观，可视区大小都是默认的没变化！

是不是用了cdn

**Comment by chwl66** [comment]
> > 我调整了博客可视区宽度，不管是调大还是调小都不起作用，都是默认宽度！换了几个外观，可视区大小都是默认的没变化！
> 
> 是不是用了cdn

cdn用的是jsdelivr的。

**Comment by UserUnknownX** [comment]
> > > 我调整了博客可视区宽度，不管是调大还是调小都不起作用，都是默认宽度！换了几个外观，可视区大小都是默认的没变化！
> > 
> > 
> > 是不是用了cdn
> 
> cdn用的是jsdelivr的。

试试去了cdn然后Ctrl+Shift+r（后面加上cdn不知道有没有影响）

**Comment by chwl66** [comment]
> > > > 我调整了博客可视区宽度，不管是调大还是调小都不起作用，都是默认宽度！换了几个外观，可视区大小都是默认的没变化！
> > > 
> > > 
> > > 是不是用了cdn
> > 
> > 
> > cdn用的是jsdelivr的。
> 
> 试试去了cdn然后Ctrl+Shift+r（后面加上cdn不知道有没有影响）

去了cdn然后再加上可以了，谢谢大佬！

**Comment by UserUnknownX** [comment]
> > > > > 我调整了博客可视区宽度，不管是调大还是调小都不起作用，都是默认宽度！换了几个外观，可视区大小都是默认的没变化！
> > > > 
> > > > 
> > > > 是不是用了cdn
> > > 
> > > 
> > > cdn用的是jsdelivr的。
> > 
> > 
> > 试试去了cdn然后Ctrl+Shift+r（后面加上cdn不知道有没有影响）
> 
> 去了cdn然后再加上可以了，谢谢大佬！

不谢 XD
