### ISSUE TITLE
页面无法正常显示

### ISSUE THREAD

**Issue by qz-cqy** [hsxyhao/gridea-theme-next#11]
我在使用NexT的时候遇到了下图中的情况，使用了家里的WiFi和手机热点都是这样，想问一下是我网的问题还是NexT的bug。网址：https://qz-cqy.github.io

![](https://cdn.luogu.com.cn/upload/image_hosting/z64eyex3.png)
![](https://s2.ax1x.com/2020/02/12/1755Tg.png)

**Comment by hsxyhao** [comment]
> 我在使用NexT的时候遇到了下图中的情况，使用了家里的WiFi和手机热点都是这样，想问一下是我网的问题还是NexT的bug。网址：https://qz-cqy.github.io
> 
> ![](https://camo.githubusercontent.com/a651bc9a59e31b47356d40bee365e964b398f415/68747470733a2f2f63646e2e6c756f67752e636f6d2e636e2f75706c6f61642f696d6167655f686f7374696e672f7a363465796578332e706e67)
> ![](https://camo.githubusercontent.com/690fac08da615fff5ac4d570ab9cf61a06581199/68747470733a2f2f73322e617831782e636f6d2f323032302f30322f31322f3137353554672e706e67)

这边是我的问题，可能是高亮的css没有加载引发的，我fix了一下，你那边在下载一下试试

**Comment by qz-cqy** [comment]
好，谢谢

**Comment by qz-cqy** [comment]
> 
> 
> > 我在使用NexT的时候遇到了下图中的情况，使用了家里的WiFi和手机热点都是这样，想问一下是我网的问题还是NexT的bug。网址：https://qz-cqy.github.io
> > ![](https://camo.githubusercontent.com/a651bc9a59e31b47356d40bee365e964b398f415/68747470733a2f2f63646e2e6c756f67752e636f6d2e636e2f75706c6f61642f696d6167655f686f7374696e672f7a363465796578332e706e67)
> > ![](https://camo.githubusercontent.com/690fac08da615fff5ac4d570ab9cf61a06581199/68747470733a2f2f73322e617831782e636f6d2f323032302f30322f31322f3137353554672e706e67)
> 
> 这边是我的问题，可能是高亮的css没有加载引发的，我fix了一下，你那边在下载一下试试

但是还是像原来那样，没变

**Comment by hsxyhao** [comment]
> > > 我在使用NexT的时候遇到了下图中的情况，使用了家里的WiFi和手机热点都是这样，想问一下是我网的问题还是NexT的bug。网址：https://qz-cqy.github.io
> > > ![](https://camo.githubusercontent.com/a651bc9a59e31b47356d40bee365e964b398f415/68747470733a2f2f63646e2e6c756f67752e636f6d2e636e2f75706c6f61642f696d6167655f686f7374696e672f7a363465796578332e706e67)
> > > ![](https://camo.githubusercontent.com/690fac08da615fff5ac4d570ab9cf61a06581199/68747470733a2f2f73322e617831782e636f6d2f323032302f30322f31322f3137353554672e706e67)
> > 
> > 
> > 这边是我的问题，可能是高亮的css没有加载引发的，我fix了一下，你那边在下载一下试试
> 
> 但是还是像原来那样，没变

你的博客已经换主题了，暂时我这边排查不出来，如果你想继续使用NexT的话，就微信(wh806649821)联系吧

**Comment by qz-cqy** [comment]
> 
> 
> > > > 我在使用NexT的时候遇到了下图中的情况，使用了家里的WiFi和手机热点都是这样，想问一下是我网的问题还是NexT的bug。网址：https://qz-cqy.github.io
> > > > ![](https://camo.githubusercontent.com/a651bc9a59e31b47356d40bee365e964b398f415/68747470733a2f2f63646e2e6c756f67752e636f6d2e636e2f75706c6f61642f696d6167655f686f7374696e672f7a363465796578332e706e67)
> > > > ![](https://camo.githubusercontent.com/690fac08da615fff5ac4d570ab9cf61a06581199/68747470733a2f2f73322e617831782e636f6d2f323032302f30322f31322f3137353554672e706e67)
> > > 
> > > 
> > > 这边是我的问题，可能是高亮的css没有加载引发的，我fix了一下，你那边在下载一下试试
> > 
> > 
> > 但是还是像原来那样，没变
> 
> 你的博客已经换主题了，暂时我这边排查不出来，如果你想继续使用NexT的话，就微信(wh806649821)联系吧

不用了，已经可以了，next主题需要图片大小为100*100像素，太大了就会有问题，建议您备注一下
