### ISSUE TITLE
建议对版权声明增加更多配置选项

### ISSUE THREAD

**Issue by alpaca-brother** [hsxyhao/gridea-theme-next#110]
如题，希望可以更改版权声明中的 链接地址（将默认地址改为解析后的地址）、更改版权声明的颜色（红色太突出了，希望能换个颜色）、更改版权声明的内容（如完全禁止转载，或者更改转载协议）

说真的，版权声明能不能完全关掉啊？这种东西只防君子，不防小人……加上去嫌他占地儿……

**Comment by alpaca-brother** [comment]
![Snipaste_2020-06-20_23-08-40](https://user-images.githubusercontent.com/50550449/85205035-171e4400-b34b-11ea-90a6-edd05e0caab0.png)
感觉这种效果略显尴尬

**Comment by o1f** [comment]
下载个编辑器,全局搜算关键词修改吧.
友情链接有单独的页面..

**Comment by alpaca-brother** [comment]
我是觉得友情链接过于简陋，才自己写的文章。
不管怎样，谢谢建议！

**Comment by alpaca-brother** [comment]
一个新的问题……
主题中有那么多文件，应该如何修改……对这一领域完全不懂，请大佬指教。

**Comment by o1f** [comment]
定位关键词 (那种不会变的)
使用编辑器(例如 Visual Studio Code)打开主题文件夹
使用全局搜索关键词,定位文件
修改文件,进行测试 

例如

![image](https://user-images.githubusercontent.com/28326356/85205602-f2c46680-b34e-11ea-81cd-dee610827d85.png)

**Comment by alpaca-brother** [comment]
非常感谢！我现在就进行修改。

**Comment by alpaca-brother** [comment]
问题解决了，非常感谢！
