### ISSUE TITLE
预览可以正常显示，同步在网页上没正常显示，如图：同步后网页上显示情况

### ISSUE THREAD

**Issue by 1198560751** [hsxyhao/gridea-theme-next#117]
![image](https://user-images.githubusercontent.com/57899844/85537742-d07c6280-b646-11ea-922c-7cf533b0d6d6.png)

**Comment by hsxyhao** [comment]
是不是设置cdn，或者配置域名的时候使用得是http不是https

**Comment by 1198560751** [comment]
没有设置cdn，配置域名的时候使用得是https。预览可以正常显示，同步后就是图片的情况。

**Comment by 1198560751** [comment]
用默认的主题在同步后可以显示。

**Comment by 1198560751** [comment]
> 是不是设置cdn，或者配置域名的时候使用得是http不是https

没有设置cdn，配置域名的时候使用得是https。预览可以正常显示，同步后就是图片的情况。用默认的主题在同步后可以显示。

**Comment by 1198560751** [comment]
> 是不是设置cdn，或者配置域名的时候使用得是http不是https

很奇怪，可以帮我看一下吗。我把这个主题删了从新下的还是一样的情况。预览可以正常显示，同步在网页上没正常显示。

**Comment by hsxyhao** [comment]
> > 是不是设置cdn，或者配置域名的时候使用得是http不是https
> 
> 很奇怪，可以帮我看一下吗。我把这个主题删了从新下的还是一样的情况。预览可以正常显示，同步在网页上没正常显示。

你发布到线上去，我去看看
