### ISSUE TITLE
每次打开 Gridea，看板娘都是开启状态

### ISSUE THREAD

**Issue by tcitry** [hsxyhao/gridea-theme-next#12]
本来已手动关闭，但是后来发现，每次打开 gridea，或者是修改某些其他配置，看板娘开关都会自己打开。
![image](https://user-images.githubusercontent.com/5220740/74408447-65887700-4e6f-11ea-8167-32608eb82db0.png)

**Comment by hsxyhao** [comment]
> 本来已手动关闭，但是后来发现，每次打开 gridea，或者是修改某些其他配置，看板娘开关都会自己打开。
> ![image](https://user-images.githubusercontent.com/5220740/74408447-65887700-4e6f-11ea-8167-32608eb82db0.png)

这个应该是配置没有保存的问题，我先排查一下，不过很有可能是gridea的bug，之前在群里看到过很多人出现配置无法保存的问题
