### ISSUE TITLE
这个主题好棒

### ISSUE THREAD

**Issue by Jerrywang959** [hsxyhao/gridea-theme-next#123]
麻烦给个捐赠链接呗, 虽然我可能也捐不了多少钱, 就是想感谢一下

**Comment by hsxyhao** [comment]
> 麻烦给个捐赠链接呗, 虽然我可能也捐不了多少钱, 就是想感谢一下

感谢支持，关于捐赠的问题在[博客上](https://yeming.site/post/about/)解释过，最后，心意领了，如果可以的话多提意见改善改善
