### ISSUE TITLE
关于《Next使用文档》

### ISSUE THREAD

**Issue by YunQian-QwQ** [hsxyhao/gridea-theme-next#126]
我记得这个教程以前是在`yeming.site`上的，不过博客搬到另一个地方之后这个文档好像就无法访问了=_=

![aXb9Rf.png](https://s1.ax1x.com/2020/08/12/aXb9Rf.png)

然后试着去新博客找，但是要命的是自家电脑抽风，登不上`.github.io`，自己博客（同样用的`.github.io`）也是搞了好半天之后，在hosts里面加了一句，才好不容易登上的=_=

![aXbEZj.png](https://s1.ax1x.com/2020/08/12/aXbEZj.png)

另外重置 DNS 貌似没毛用，还是登不上`.github.io`

所以这里能不能请博主把这文章复制到这个github仓库里啊=_=，不然实在是看不了了......

**Comment by hsxyhao** [comment]
> 我记得这个教程以前是在`yeming.site`上的，不过博客搬到另一个地方之后这个文档好像就无法访问了=_=
> 
> ![aXb9Rf.png](https://camo.githubusercontent.com/366baf53b14747f6a4f8b95fe6ba098857d17b76/68747470733a2f2f73312e617831782e636f6d2f323032302f30382f31322f6158623952662e706e67)
> 
> 然后试着去新博客找，但是要命的是自家电脑抽风，登不上`.github.io`，自己博客（同样用的`.github.io`）也是搞了好半天之后，在hosts里面加了一句，才好不容易登上的=_=
> 
> ![aXbEZj.png](https://camo.githubusercontent.com/6e5fcc42ca240da4b44b18ecf234260baeb626a2/68747470733a2f2f73312e617831782e636f6d2f323032302f30382f31322f615862455a6a2e706e67)
> 
> 另外重置 DNS 貌似没毛用，还是登不上`.github.io`
> 
> 所以这里能不能请博主把这文章复制到这个github仓库里啊=_=，不然实在是看不了了......

这个仓库[hsxyhao.github.io](https://github.com/hsxyhao/hsxyhao.github.io)可以访问吗，开源项目放一些私有的东西感觉不是很好
