### ISSUE TITLE
[已解决] 代码块高亮主题名称需要对照themes/next/assets/media/hljs/styles查看 && fancybox图片查看bug

### ISSUE THREAD

**Issue by doubleLLL3** [hsxyhao/gridea-theme-next#133]
作者您好！代码块高亮主题需要自己改为小写，这个您也许可以帮大家避开这个坑 😄 

[PS] 很感谢您很快把图片沙盒安排上了，不过确实兼容性有些问题，一些图片都堆到最后面了~

**Comment by doubleLLL3** [comment]
另外名字有空格的主题，比如Stackoverflow Dark [stackoverflow dark]，我还没找到方法应用上，尝试了下面几种方法
① 空格用_代替
② 空格用-代替
③ 空格用&nbsp;代替
④ 双引号""包围主题名称
⑤ 单引号''包围主题名称
⑥ 转义符\转义空格

**Comment by hsxyhao** [comment]
> 作者您好！代码块高亮主题需要自己改为小写，这个您也许可以帮大家避开这个坑 😄
> 
> [PS] 很感谢您很快把图片沙盒安排上了，不过确实兼容性有些问题，一些图片都堆到最后面了~

最好给个截图，我测试的时候除了展示有些慢（和cdn有关）其他的还好，你那边的问题我还没遇见过，还有代码块的高亮主题，是不是操作上有差异，我之前切换高亮主题好像没有这么多修改

**Comment by doubleLLL3** [comment]
① 可以理解为：本来是[图片]文字[图片]文字，变成了[图片]文字[图片]文字[图片图片图片]，就是一些图片全部堆到最后面了
PS：我已经换回来旧主题了，如果你想要什么具体的信息，我愿意换回去找找，看你有没有需要的具体信息
② 高亮主题我是在gridea——主题——自定义配置——特性——代码块高亮主题下改的，比如我用的主题是Agate，我要填写agate，而不是Agate [不生效]，然后对于有空格的主题，没试出来合适的表达。
另外，我用的主题是Muse

**Comment by doubleLLL3** [comment]
不知道博主是否方便实现fancybox，看起来也是用来看图片的，效果不错；
或者您指点一下，自己加入fancybox这类插件的话的话，需要改哪些地方？

**Comment by doubleLLL3** [comment]
作者您好，我找到了图片混乱的一些规律，因为我的md文档是在typora里写的，现在发现对于`图片格式为html语法且没有列表化`的图片，在博客上就会被堆在文档的最后。
现在的效果是这样的：这些图片本来插在文档中间的部分
![image](https://user-images.githubusercontent.com/44157339/102715008-66026180-430d-11eb-9f78-e59bf47b202f.png)
它们对应的共同特点如下：用了html语法，但没有列表化
![image](https://user-images.githubusercontent.com/44157339/102714931-ff7d4380-430c-11eb-87ee-b3f2bd2023e4.png)
而其他正确放置的图片是长这样：
用了html语法，但是是列表
![image](https://user-images.githubusercontent.com/44157339/102714966-305d7880-430d-11eb-9a13-ef745fad80f6.png)
不是列表，但是用的md语法
![image](https://user-images.githubusercontent.com/44157339/102715107-f8a30080-430d-11eb-9c44-a7e48c6f7177.png)

目前解决方案就是：只要用了html语法就用列表的形式~

**Comment by hsxyhao** [comment]
> 作者您好，我找到了图片混乱的一些规律，因为我的md文档是在typora里写的，现在发现对于`图片格式为html语法且没有列表化`的图片，在博客上就会被堆在文档的最后。
> 现在的效果是这样的：这些图片本来插在文档中间的部分
> ![image](https://user-images.githubusercontent.com/44157339/102715008-66026180-430d-11eb-9f78-e59bf47b202f.png)
> 它们对应的共同特点如下：用了html语法，但没有列表化
> ![image](https://user-images.githubusercontent.com/44157339/102714931-ff7d4380-430c-11eb-87ee-b3f2bd2023e4.png)
> 而其他正确放置的图片是长这样：
> 用了html语法，但是是列表
> ![image](https://user-images.githubusercontent.com/44157339/102714966-305d7880-430d-11eb-9a13-ef745fad80f6.png)
> 不是列表，但是用的md语法
> ![image](https://user-images.githubusercontent.com/44157339/102715107-f8a30080-430d-11eb-9c44-a7e48c6f7177.png)
> 
> 目前解决方案就是：只要用了html语法就用列表的形式~

这个bug我应该知道了，算法处理的有问题，我后面改下

**Comment by doubleLLL3** [comment]
太棒了！用上最新的版本，fancybox更fancy了。
[PS]不过最近遇到一个问题，就是Valine不自动添加Counter了？
![image](https://user-images.githubusercontent.com/44157339/102792045-e0e97c00-43e2-11eb-9039-4ae74971d21c.png)
现在LeanCloud上有39个Counters，从38开始就是自己手动添加的了，请教博主是哪个环节出问题了呢~

**Comment by doubleLLL3** [comment]
可能是当天的限额用完了之类的，刚刚过了零点，再访问上就创建好Counter了
打扰了...
