### ISSUE TITLE
关于鼠标指针的问题

### ISSUE THREAD

**Issue by zxmav** [hsxyhao/gridea-theme-next#136]
打扰了，大佬，我这边按照你的[文档.md](https://github.com/hsxyhao/gridea-theme-next/blob/master/%E6%96%87%E6%A1%A3.md)这个去做了，但是鼠标还是没法显示出来。
图片：
![图片](https://camo.githubusercontent.com/b835895f96dd8c697f3099e6d384e96d91f74163754176ff3d6ea65a9eb677aa/68747470733a2f2f7570696d6167652e616c6578686368752e636f6d2f323032302f30342f32332f663730636131656132653763632e706e67)
![图片](https://upimage.alexhchu.com/2021/01/23/c356b6b10a74d.png)

**Comment by hsxyhao** [comment]
> 打扰了，大佬，我这边按照你的[文档.md](https://github.com/hsxyhao/gridea-theme-next/blob/master/%E6%96%87%E6%A1%A3.md)这个去做了，但是鼠标还是没法显示出来。
> 图片：
> ![图片](https://camo.githubusercontent.com/b835895f96dd8c697f3099e6d384e96d91f74163754176ff3d6ea65a9eb677aa/68747470733a2f2f7570696d6167652e616c6578686368752e636f6d2f323032302f30342f32332f663730636131656132653763632e706e67)
> ![图片](https://camo.githubusercontent.com/9072e8b1cb9721535ea4a25208367a58af058959fabb64980f5df7a2fae1f1bb/68747470733a2f2f7570696d6167652e616c6578686368752e636f6d2f323032312f30312f32332f633335366236623130613734642e706e67)

1. 看看鼠标有没有后缀
2. 还有看看鼠标的资源有没有上传成功，能不能访问到
3. 或者把博客地址留下来

**Comment by zxmav** [comment]
鼠标用的是默认的那套，填写的话没后缀，然后图2左侧是我的仓库,已经上传了，仓库地址是https://github.com/zxmav/zxmav.github.io，博客地址是https://www.zxmacc.cf/,麻烦了

**Comment by zxmav** [comment]
https://github.com/zxmav/zxmav.github.io
https://www.zxmacc.cf/

**Comment by zxmav** [comment]
我去把output和仓库删了，重来一遍试试

**Comment by zxmav** [comment]
鼠标上传了，但是还是不行

**Comment by zxmav** [comment]
成功了？但是背景图像没了
