### ISSUE TITLE
修改配置后不能保存

### ISSUE THREAD

**Issue by TYtangyi** [hsxyhao/gridea-theme-next#140]
自定义配置中评论开关关闭后，不能保存

**Comment by hsxyhao** [comment]
在windows下，使用背景图片就会导致保存配置失败的情况，可以先保存配置在上传背景，这个是gridea的一个bug

**Comment by hsxyhao** [comment]
> 自定义配置中评论开关关闭后，不能保存

在windows下，使用背景图片就会导致保存配置失败的情况，可以先保存配置在上传背景，这个是gridea的一个bug

**Comment by xiaoyangst** [comment]
> > 自定义配置中评论开关关闭后，不能保存
> 
> 在windows下，使用背景图片就会导致保存配置失败的情况，可以先保存配置在上传背景，这个是gridea的一个bug

那太离谱了，以后那不都得把背景删除再去保存？
