### ISSUE TITLE
要不要考虑搞一个 halo 版本的 next

### ISSUE THREAD

**Issue by Jalr4ever** [hsxyhao/gridea-theme-next#141]
如题，最近发现，经过 gridea 的编译，每一篇博客的内容都会编译到 html，现在每个 html 就 900k 左右那么大了，非常耗费服务器资源

而且 gredia 的社区并不是特别活跃，好久没更新，最近考虑在迁移到动态博客 halo 了，无奈 halo 官方适配的 next 的样式感觉可定制的内容太少了... 有没有考虑将本主题为 halo 适配一下呢？

**Comment by hsxyhao** [comment]
> 如题，最近发现，经过 gridea 的编译，每一篇博客的内容都会编译到 html，现在每个 html 就 900k 左右那么大了，非常耗费服务器资源
> 
> 而且 gredia 的社区并不是特别活跃，好久没更新，最近考虑在迁移到动态博客 halo 了，无奈 halo 官方适配的 next 的样式感觉可定制的内容太少了... 有没有考虑将本主题为 halo 适配一下呢？

先了解一下吧，看看能不能出一个

**Comment by Jalr4ever** [comment]
> > 如题，最近发现，经过 gridea 的编译，每一篇博客的内容都会编译到 html，现在每个 html 就 900k 左右那么大了，非常耗费服务器资源
> > 而且 gredia 的社区并不是特别活跃，好久没更新，最近考虑在迁移到动态博客 halo 了，无奈 halo 官方适配的 next 的样式感觉可定制的内容太少了... 有没有考虑将本主题为 halo 适配一下呢？
> 
> 先了解一下吧，看看能不能出一个

期待！可以先看看官方已经适配的那个 next，看着是前端模版语言写的，加油啊！

**Comment by hsxyhao** [comment]
> halo

halo上面的Next主题已经存在过了，我现在也不好重新开发一个了，不过我一直有打算开发一个基于云端的hexo博客部署网站，这样hexo上所有的主题都可以使用，不用搬运。
不过现实还有很多东西没确定，gridea的生态确是起不来了

**Comment by hsxyhao** [comment]
> halo

halo上面的Next主题已经存在过了，我现在也不好重新开发一个了，不过我一直有打算开发一个基于云端的hexo博客部署网站，这样hexo上所有的主题都可以使用，不用搬运，不过这个工程量有点大，暂时还不太有信心弄起来
不过现实还有很多东西没确定，gridea的生态确是起不来了

**Comment by hsxyhao** [comment]
> halo

halo上面的Next主题已经存在过了，我现在也不好重新开发一个了，不过我一直有打算开发一个基于云端的hexo博客部署网站，这样hexo上所有的主题都可以使用，不用搬运，不过这个工程量（前期开发，后期运营，费用这些）有点大，暂时还不太有信心弄起来
不过现实还有很多东西没确定，gridea的生态确是起不来了

**Comment by Jalr4ever** [comment]
> > halo
> 
> halo上面的Next主题已经存在过了，我现在也不好重新开发一个了，不过我一直有打算开发一个基于云端的hexo博客部署网站，这样hexo上所有的主题都可以使用，不用搬运。
> 不过现实还有很多东西没确定，gridea的生态确是起不来了

就 fork 一下它，做一个更好的，因为 halo 现在的那个比你现在做的差太多了，halo 上面的那个根本没有发挥出 halo 的所有功能，可定制性也比你的差很多

目前在 gridea 平台我大概就是 79 篇博客，每一篇博客编译出一个 html 文件高达 900kb 左右，足足 79 个 html，看了眼我这才发现，gridea 把每篇博客的内容混在同一个 html 了。。。我也不知道为何它要这么做，但由于我现在是用 SFTP 同步到个人服务器，流量计费的，每次都要上传一下，这样子以后几百篇博客还得了？

得知静态博客不大靠谱，于是就一直在调研动态博客，后面发现 halo 部署很方便，数据迁移也算方便，因为是动态博客，搜索的功能也不用把文章加载到浏览器缓存了，跪求博主搞一个加强版 next 啊
