### ISSUE TITLE
LaTeX 重复显示公式

### ISSUE THREAD

**Issue by hexarhy** [hsxyhao/gridea-theme-next#142]
[传送门。](https://hexarhy.github.io/post/UVA10428/)一句渲染好了，会重复出现了一句没有渲染的公式。

以及主题内的 config 不知道为什么没有 LaTeX 的选项，后来自己加的 KaTeX。

**Comment by hsxyhao** [comment]
> [传送门。](https://hexarhy.github.io/post/UVA10428/)一句渲染好了，会重复出现了一句没有渲染的公式。
> 
> 以及主题内的 config 不知道为什么没有 LaTeX 的选项，后来自己加的 KaTeX。
换一个latex插件试试，之前有人也遇到过
