### ISSUE TITLE
markdown渲染后有些地方加粗失败

### ISSUE THREAD

**Issue by kIl3rr** [hsxyhao/gridea-theme-next#143]
![图片](https://user-images.githubusercontent.com/74661756/123521277-3f701980-d6e8-11eb-8f0c-e3090559891e.png)

另外前面有人已经提及 不能保存配置的问题 望解决

**Comment by hsxyhao** [comment]
> ![图片](https://user-images.githubusercontent.com/74661756/123521277-3f701980-d6e8-11eb-8f0c-e3090559891e.png)
> 
> 另外前面有人已经提及 不能保存配置的问题 望解决

不能保存配置已经有过很详细的说明了，这个问题根本原因是由于gridea软件本身的bug导致的，加粗失败到是没有遇见过，把你的那块内容贴出来看下

**Comment by Nul10** [comment]
![图片](https://user-images.githubusercontent.com/74661756/124222705-d7309600-db34-11eb-8ee1-e48c92c682f5.png)
![图片](https://user-images.githubusercontent.com/74661756/124222751-eca5c000-db34-11eb-913a-16e678bbb926.png)
代码块有些地方的代码也会莫名加粗
