### ISSUE TITLE
HKplayer失效

### ISSUE THREAD

**Issue by YuZhangWang** [hsxyhao/gridea-theme-next#147]
测试现在HKplayer已经失效了 点击该选项 网站渲染出来是没有播放器的

**Comment by hsxyhao** [comment]
> 测试现在HKplayer已经失效了 点击该选项 网站渲染出来是没有播放器的
回来看看怎么回事

**Comment by YuZhangWang** [comment]
> > 测试现在HKplayer已经失效了 点击该选项 网站渲染出来是没有播放器的
> 回来看看怎么回事

可能是 player.js的问题 访问不了这个文件，应该是开发者换了接口之类的

**Comment by YuZhangWang** [comment]
> > 测试现在HKplayer已经失效了 点击该选项 网站渲染出来是没有播放器的
> 回来看看怎么回事

我去作者官网看了一下，他原来是放了一个.js文件，但现在他把这个变成了一串代码
现在我进行的操作是注册他的官网，然后去里面复制他新的代码插件 再手动添加到页面里面。

**Comment by hsxyhao** [comment]
> > > 测试现在HKplayer已经失效了 点击该选项 网站渲染出来是没有播放器的
> > > 回来看看怎么回事
> 
> 我去作者官网看了一下，他原来是放了一个.js文件，但现在他把这个变成了一串代码
> 现在我进行的操作是注册他的官网，然后去里面复制他新的代码插件 再手动添加到页面里面。

资源链接换了，已经在修复了，晚点同步一下

**Comment by YuZhangWang** [comment]
> > > > 测试现在HKplayer已经失效了 点击该选项 网站渲染出来是没有播放器的
> > > > 回来看看怎么回事
> > 
> > 我去作者官网看了一下，他原来是放了一个.js文件，但现在他把这个变成了一串代码
> > 现在我进行的操作是注册他的官网，然后去里面复制他新的代码插件 再手动添加到页面里面。
> 
> 资源链接换了，已经在修复了，晚点同步一下

可以可以
