### ISSUE TITLE
http和https协议

### ISSUE THREAD

**Issue by YuZhangWang** [hsxyhao/gridea-theme-next#149]
目前默认渲染出来的是http协议格式的 这样会导致网站有不安全元素产生 即使添加了ssl证书 开启强制https模式 网站也会不安全 需要手动将全部的http改成https才行

**Comment by hsxyhao** [comment]
> 目前默认渲染出来的是http协议格式的 这样会导致网站有不安全元素产生 即使添加了ssl证书 开启强制https模式 网站也会不安全 需要手动将全部的http改成https才行

这个可以在配置远程域名那里直接改成自定义的域名，渲染不是主题实现的，是gridea底层做的

**Comment by YuZhangWang** [comment]
> 
> 
> > 目前默认渲染出来的是http协议格式的 这样会导致网站有不安全元素产生 即使添加了ssl证书 开启强制https模式 网站也会不安全 需要手动将全部的http改成https才行
> 
> 这个可以在配置远程域名那里直接改成自定义的域名，渲染不是主题实现的，是gridea底层做的

现在Gridea远程链接有问题 试过您博客上的方法 还是无效 现在写完博客自己在websotrm里面改
同步不了 渲染还是有问题
