### ISSUE TITLE
请问您的next主题的Pisces外观如何设置三个大板块的透明度呢？https://8421bcd.github.io/（这个是我的目前没有设置透明度的），https://piggyzhl.top/(这个是有透明度的)

### ISSUE THREAD

**Issue by 8421BCD** [hsxyhao/gridea-theme-next#15]
如果是改透明度的话应该在哪个文件中修改呢？

**Comment by hsxyhao** [comment]
> 如果是改透明度的话应该在哪个文件中修改呢？

![image](https://user-images.githubusercontent.com/22101306/74605850-a2ba6680-5106-11ea-8055-09a0d8120b4e.png)
这里有修改透明度的设置

**Comment by 8421BCD** [comment]
请问您的gridea的版本?
![image](https://user-images.githubusercontent.com/55248222/74605938-43108b00-5107-11ea-9f2a-5ecafd376b92.png)

**Comment by 8421BCD** [comment]
我的是0.9.1版本的，没有这个修改透明度的功能

**Comment by hsxyhao** [comment]
> 我的是0.9.1版本的，没有这个修改透明度的功能

版本是0.9.0，但是这个是自定义配置，和主题的版本有关系，你主题下载的是最新的吗？我这边先把gridea更新到最新的版本看下

**Comment by 8421BCD** [comment]
放不方便加个QQ或者微信细聊?

**Comment by 8421BCD** [comment]
我更新next解决了 谢谢

**Comment by hsxyhao** [comment]
> 我更新next解决了 谢谢

vx: wh806649821（备注Next），后期如果在有使用上的问题，可以微信联系，bug的话可以直接issue，方便其他网友查看^^
