### ISSUE TITLE
关于标签问题

### ISSUE THREAD

**Issue by YuZhangWang** [hsxyhao/gridea-theme-next#152]
实测添加新标签的时候会失效
看了一下输出文件里面，在新的添加标签</a>后面 会多出来一个中文的顿号 把这个顿号去了再运行测试标签就没有问题
希望开发者能够检查一下标签添加 渲染的代码是不是出了问题 为什么会多出一个顿号？

**Comment by hsxyhao** [comment]
> 实测添加新标签的时候会失效
> 看了一下输出文件里面，在新的添加标签后面 会多出来一个中文的顿号 把这个顿号去了再运行测试标签就没有问题
> 希望开发者能够检查一下标签添加 渲染的代码是不是出了问题 为什么会多出一个顿号？

方便截图吗？这边没有复现

**Comment by YuZhangWang** [comment]
> > 实测添加新标签的时候会失效
> > 看了一下输出文件里面，在新的添加标签后面 会多出来一个中文的顿号 把这个顿号去了再运行测试标签就没有问题
> > 希望开发者能够检查一下标签添加 渲染的代码是不是出了问题 为什么会多出一个顿号？
> 
> 方便截图吗？这边没有复现

![IMG_20210825_142610.jpg](https://user-images.githubusercontent.com/65295250/130737787-fe07989f-a618-433f-810b-0de18f898beb.jpg)
![IMG_20210825_142620.jpg](https://user-images.githubusercontent.com/65295250/130737798-eaa862de-b884-4c27-8179-de65450b40f0.jpg)
![IMG_20210825_142635.jpg](https://user-images.githubusercontent.com/65295250/130737813-b7b0bed4-9ec8-4c68-b7a4-489b2770212e.jpg)
![IMG_20210825_142653.jpg](https://user-images.githubusercontent.com/65295250/130737832-043831af-f58a-4295-803d-716464b0f9a6.jpg)

之前用next主题的时候，一直没有添加新标签，所以没有发现这个问题，最近刚好添加了新标签，在测试网站的时候，点击文章上面的标签和标签栏出现的标签就会出现404，看了一下出错的标签，都是以下划线开头命名的，之前用别的主题创建的标签，都是没有下划线的随机数字

**Comment by YuZhangWang** [comment]
> > 实测添加新标签的时候会失效
> > 看了一下输出文件里面，在新的添加标签后面 会多出来一个中文的顿号 把这个顿号去了再运行测试标签就没有问题
> > 希望开发者能够检查一下标签添加 渲染的代码是不是出了问题 为什么会多出一个顿号？
> 
> 方便截图吗？这边没有复现

![IMG_20210825_142959.jpg](https://user-images.githubusercontent.com/65295250/130738126-eee6654f-f156-4272-a5e8-c8ad707bcb52.jpg)
看了一下代码应该和顿号没关系，顿号是一篇文章有多个标签，所以用顿号来分隔开。不过在next主题下，新建标签所产生的标签链接会指向404访问不了。课程设计就是新添加的标签是以下划线开头的，数据结构是之前添加的，是以字母开头的

**Comment by YuZhangWang** [comment]
刚才网站有点崩 现在已经好了 可以查看一下这个标签的bug https://www.yuzhang.wang/
![Screenshot_20210825-162226.jpg](https://user-images.githubusercontent.com/65295250/130755032-49aacecd-353e-4770-9da5-6c70d216d16e.jpg)
![Screenshot_20210825-162230.jpg](https://user-images.githubusercontent.com/65295250/130755056-38b9b72b-5ebe-4429-9e20-bda00eab6db9.jpg)
![Screenshot_20210825-162239.jpg](https://user-images.githubusercontent.com/65295250/130755075-8fec6487-ea69-4fb9-b30f-518a8144074b.jpg)
