### ISSUE TITLE
非常喜欢的主题，请问目录怎么添加？

### ISSUE THREAD

**Issue by CengJia** [hsxyhao/gridea-theme-next#154]

**Comment by hsxyhao** [comment]
> _No description provided._

目录的添加需要参考gridea的文档

**Comment by CengJia** [comment]
查到了是这个命令@[toc]，但是加了完全没有效果。我是不会网页开发的人。。。。

**Comment by hsxyhao** [comment]
> 查到了是这个命令@[toc]，但是加了完全没有效果。我是不会网页开发的人。。。。
自动支持的，不需要添加，toc这个命令不支持

**Comment by CengJia** [comment]
所以是怎么搞出文章内目录呢？搞了一下午都没搞出来
