### ISSUE TITLE
提示文本错误

### ISSUE THREAD

**Issue by LeUKi** [hsxyhao/gridea-theme-next#17]
![image](https://user-images.githubusercontent.com/34953046/75149623-7376ab80-573d-11ea-9028-50689630f446.png)
应该是 github：fa-github-alt

**Comment by hsxyhao** [comment]
> ![image](https://user-images.githubusercontent.com/34953046/75149623-7376ab80-573d-11ea-9028-50689630f446.png)
> 应该是 github：fa-github-alt

感谢提醒
