### ISSUE TITLE
建议 能否添加Valine评论系统

### ISSUE THREAD

**Issue by qz-cqy** [hsxyhao/gridea-theme-next#18]
Next主题能否添加Valine评论系统？Gitalk之类的不太方便，谢谢！

**Comment by hsxyhao** [comment]
> Next主题能否添加Valine评论系统？Gitalk之类的不太方便，谢谢！

可以，不过排期需要靠后些

**Comment by Mornwind** [comment]
看到新加的Valine评论系统了，试用了下，能正常工作。
