### ISSUE TITLE
Aplayer Cover image not fount

### ISSUE THREAD

**Issue by ame1973** [hsxyhao/gridea-theme-next#19]
音樂添加 Cover 图片后显示并没有显示

> Chrome Version 79.0.3945.130 (Official Build) (64-bit)

出現以下錯誤:
> Failed to load resource: the server responded with a status of 404 (Not Found)

> GET http://localhost:4000/mediaimages%0Custom-cover.jpg 404 (Not Found)

config 中儲存的是
`"cover":"\\media\\images\\custom-cover.jpg"`

**Comment by hsxyhao** [comment]
> 音樂添加 Cover 图片后显示并没有显示
> 
> > Chrome Version 79.0.3945.130 (Official Build) (64-bit)
> 
> 出現以下錯誤:
> 
> > Failed to load resource: the server responded with a status of 404 (Not Found)
> 
> > GET http://localhost:4000/mediaimages%0Custom-cover.jpg 404 (Not Found)
> 
> config 中儲存的是
> `"cover":"\\media\\images\\custom-cover.jpg"`

音乐那个链接填网络链接，本地的话是不会上传到，mp3资源也是网络资源

**Comment by ame1973** [comment]
Cover 图片一栏只能选择上传本地图片。
![Capture](https://user-images.githubusercontent.com/32356815/75572134-85d24b80-5a95-11ea-9e16-5696dcd7148d.PNG)

问题是上传了本地图片后，网页读取的路径并不是 `\media\images\custom-cover.jpg` 而是 `mediaimages%0Custom-cover.jpg`

我自己进入輸入URL `http://localhost:4000/media/images/Custom-cover.jpg` 是可以进入浏览到图片

**Comment by hsxyhao** [comment]
> > 音乐那个链接填网络链接，本地的话是不会上传到，mp3资源也是网络资源
> 
> Cover 图片一栏只能选择上传本地图片。
> 
> ![Capture](https://user-images.githubusercontent.com/32356815/75572134-85d24b80-5a95-11ea-9e16-5696dcd7148d.PNG)
> 
> 问题是上传了本地图片后，网页读取的路径并不是 `\media\images\custom-cover.jpg` 而是 `mediaimages%0Custom-cover.jpg`
> 
> 我自己进入輸入URL `http://localhost:4000/media/images/Custom-cover.jpg` 是可以进入浏览到图片

是的，之前是我看错了，我现在找下原因

**Comment by hsxyhao** [comment]
> > > 音乐那个链接填网络链接，本地的话是不会上传到，mp3资源也是网络资源
> > 
> > 
> > Cover 图片一栏只能选择上传本地图片。
> > ![Capture](https://user-images.githubusercontent.com/32356815/75572134-85d24b80-5a95-11ea-9e16-5696dcd7148d.PNG)
> > 问题是上传了本地图片后，网页读取的路径并不是 `\media\images\custom-cover.jpg` 而是 `mediaimages%0Custom-cover.jpg`
> > 我自己进入輸入URL `http://localhost:4000/media/images/Custom-cover.jpg` 是可以进入浏览到图片
> 
> 是的，之前是我看错了，我现在找下原因
封面无法显示可能有两个原因：
1. windows下的系统路径会被css转义，导致无法识别。在windows下上传的路径为/，mac系统下为\，windows下会进行转义，mac则不会，所以windows下的系统路径会无法识别。
2. 至于你这边的问题应该是gridea的上传有问题，上传的路径有点不对
目前这两种情况都会导致aplayer封面不会显示，后面我会找作者看看能不能修复下
