### ISSUE TITLE
引用部分符号和内容会有重叠

### ISSUE THREAD

**Issue by qiaoxu123** [hsxyhao/gridea-theme-next#2]
![image](https://user-images.githubusercontent.com/25050767/71637278-b9514f00-2c79-11ea-948c-febfb819b9c5.png)

如图片所示，引号与内容重叠了

**Comment by hsxyhao** [comment]
> ![image](https://user-images.githubusercontent.com/25050767/71637278-b9514f00-2c79-11ea-948c-febfb819b9c5.png)
> 
> 如图片所示，引号与内容重叠了

兼容性有点不到位，后续会改进，敬请期待下一次更新
