### ISSUE TITLE
目录锚点跳转无效

### ISSUE THREAD

**Issue by ame1973** [hsxyhao/gridea-theme-next#21]
当开启 音乐 > Aplayer 功能后，目录跳转点击没有任何反应。

关闭 Aplayer 就可以正常跳转页内标题

**Comment by hsxyhao** [comment]
> 当开启 音乐 > Aplayer 功能后，目录跳转点击没有任何反应。
> 
> 关闭 Aplayer 就可以正常跳转页内标题

有点问题，我看一下怎么解决
