### ISSUE TITLE
看板娘消失了!

### ISSUE THREAD

**Issue by Miuyou** [hsxyhao/gridea-theme-next#23]
预览的时候有的,一开始也是有的,后来增加了图片音乐之类的,看板娘就消失惹!

呜呜呜~~~

不过主题做的很棒哦!

**Comment by hsxyhao** [comment]
> 预览的时候有的,一开始也是有的,后来增加了图片音乐之类的,看板娘就消失惹!
> 
> 呜呜呜~~~
> 
> 不过主题做的很棒哦!

没明白你描述的场景，图片是背景图片吗？音乐是看板娘的还是aplayer的音乐？

**Comment by Miuyou** [comment]
> > 预览的时候有的，一开始也是有的，后来增加了图片音乐之类的，看板娘就消失惹！
> > 呜呜呜~~~
> > 不过主题做的很棒哦！
> 
> 没明白你描述的场景，图片是背景图片吗？音乐是看板娘的还是aplayer的音乐？

是的,音乐是aplayer的音乐

**Comment by hsxyhao** [comment]
> > > 预览的时候有的，一开始也是有的，后来增加了图片音乐之类的，看板娘就消失惹！
> > > 呜呜呜~~~
> > > 不过主题做的很棒哦！
> > 
> > 
> > 没明白你描述的场景，图片是背景图片吗？音乐是看板娘的还是aplayer的音乐？
> 
> 是的,音乐是aplayer的音乐

好的，我这边排查一下

**Comment by Miuyou** [comment]
> > > > 预览的时候有的，一开始也是有的，后来增加了图片音乐之类的，看板娘就消失惹！
> > > > 呜呜呜~~~
> > > > 不过主题做的很棒哦！
> > > 
> > > 
> > > 没明白你描述的场景，图片是背景图片吗？音乐是看板娘的还是aplayer的音乐？
> > 
> > 
> > 是的,音乐是aplayer的音乐
> 
> 好的，我这边排查一下

谢谢,就是预览有看板娘实际上却没有

**Comment by hsxyhao** [comment]
> > > > > 预览的时候有的，一开始也是有的，后来增加了图片音乐之类的，看板娘就消失惹！
> > > > > 呜呜呜~~~
> > > > > 不过主题做的很棒哦！
> > > > 
> > > > 
> > > > 没明白你描述的场景，图片是背景图片吗？音乐是看板娘的还是aplayer的音乐？
> > > 
> > > 
> > > 是的,音乐是aplayer的音乐
> > 
> > 
> > 好的，我这边排查一下
> 
> 谢谢,就是预览有看板娘实际上却没有

好了，你下载最新版本的试一下

**Comment by Miuyou** [comment]
> > > > > > 预览的时候有的，一开始也是有的，后来增加了图片音乐之类的，看板娘就消失惹！
> > > > > > 呜呜呜~~~
> > > > > > 不过主题做的很棒哦！
> > > > > 
> > > > > 
> > > > > 没明白你描述的场景，图片是背景图片吗？音乐是看板娘的还是aplayer的音乐？
> > > > 
> > > > 
> > > > 是的,音乐是aplayer的音乐
> > > 
> > > 
> > > 好的，我这边排查一下
> > 
> > 
> > 谢谢,就是预览有看板娘实际上却没有
> 
> 好了，你下载最新版本的试一下

请问是更新了吗?我是今天下的QAQ

**Comment by Miuyou** [comment]
欸,更新了,谢谢
