### ISSUE TITLE
建议版本号更新

### ISSUE THREAD

**Issue by ame1973** [hsxyhao/gridea-theme-next#27]
https://github.com/hsxyhao/gridea-theme-next/blob/3492b05a21cfd30be52e60731262bad9f5f67e56/config.json#L3

在gridea内的版本号还是显示 v 0.0.1

**Comment by hsxyhao** [comment]
> https://github.com/hsxyhao/gridea-theme-next/blob/3492b05a21cfd30be52e60731262bad9f5f67e56/config.json#L3
> 
> 在gridea内的版本号还是显示 v 0.0.1

我的锅，我的锅
