### ISSUE TITLE
左边目录导航描点不准

### ISSUE THREAD

**Issue by zhenguozhao** [hsxyhao/gridea-theme-next#29]
你好，如图目录导航页面滚动描点不准确，希望大神抽空看看

[e2e5f9ef7843971fe2efcd43f74181c3.png](http://md.storage.zhenguozhao.tech/e2e5f9ef7843971fe2efcd43f74181c3.png)

**Comment by hsxyhao** [comment]
> 你好，如图目录导航页面滚动描点不准确，希望大神抽空看看
> 
> [e2e5f9ef7843971fe2efcd43f74181c3.png](http://md.storage.zhenguozhao.tech/e2e5f9ef7843971fe2efcd43f74181c3.png)

目前的导航栏的标签需要从1~6依次写，如果中间有跳级的，就会发生这种情况，我先加到TodoList中吧

**Comment by zhenguozhao** [comment]
嗯嗯，一般情况下导航第一级都没有（习惯，或许是多数人的习惯），希望后面兼容性越来越强 👍

**Comment by hsxyhao** [comment]
处理结果：目前只能处理第一级目录不是#开始，后面必须还是要顺序处理，待优化
