### ISSUE TITLE
关于CDN 的一些建议 

### ISSUE THREAD

**Issue by deicol** [hsxyhao/gridea-theme-next#30]
之前跟作者提过 CDN，意思就是把css，js 静态资源改成外部引用。
放到云储存或者 使用 github +jsdelivr 托管 。这样无须域名备案，也可加快加载速度。

类似以下https://cdn.jsdelivr.net/gh/deicol/bref_img/2020/03/08/3a0c6342fd1014bbb66de1d4314dc0c2.png

大部分Gridea 用户托管在 github ，加载速度慢，如果其他静态资源加速，这样加载速度就会很快 。

github + jsdelivr 参考文章
 https://www.itrhx.com/2019/02/10/A18-free-cdn/
参考 gridea 主题项目 
https://github.com/ITJoker233/Gridea-theme-Chic

愿生活愉快。

ps. 现版本用户也可以自己把静态放到云存储或使用 github +jsdelivr 托管，然后修改主题静态资源路径 。

**Comment by hsxyhao** [comment]
> 之前跟作者提过 CDN，意思就是把css，js 静态资源改成外部引用。
> 放到云储存或者 使用 github +jsdelivr 托管 。这样无须域名备案，也可加快加载速度。
> 
> 类似以下https://cdn.jsdelivr.net/gh/deicol/bref_img/2020/03/08/3a0c6342fd1014bbb66de1d4314dc0c2.png
> 
> 大部分Gridea 用户托管在 github ，加载速度慢，如果其他静态资源加速，这样加载速度就会很快 。
> 
> github + jsdelivr 参考文章
> https://www.itrhx.com/2019/02/10/A18-free-cdn/
> 参考 gridea 主题项目
> https://github.com/ITJoker233/Gridea-theme-Chic
> 
> 愿生活愉快。
> 
> ps. 现版本用户也可以自己把静态放到云存储或使用 github +jsdelivr 托管，然后修改主题静态资源路径 。

mark
