### ISSUE TITLE
[Bug反馈] 文章页面中，目录的高亮条目与当前文章阅读位置总有严重的错位（见附图）

### ISSUE THREAD

**Issue by Mornwind** [hsxyhao/gridea-theme-next#31]
如下面三张图所示，可以看到，目录高亮比正文要晚1～2个标题。

![C3C05C02-99FE-4C4B-B801-B414B65F7677](https://user-images.githubusercontent.com/38060040/76167377-21a03d80-61a1-11ea-9e76-8418272d385f.jpeg)
![DC86BAB3-E515-476B-B27B-96159A215327](https://user-images.githubusercontent.com/38060040/76167380-236a0100-61a1-11ea-80d3-e6396ef57a3c.jpeg)
![E2C3C7F6-EE81-4716-8CB7-9ABE0FE4A211](https://user-images.githubusercontent.com/38060040/76167381-24029780-61a1-11ea-805a-62a3a91335aa.jpeg)

**Comment by hsxyhao** [comment]
> 如下面三张图所示，可以看到，目录高亮比正文要晚1～2个标题。
> 
> ![C3C05C02-99FE-4C4B-B801-B414B65F7677](https://user-images.githubusercontent.com/38060040/76167377-21a03d80-61a1-11ea-9e76-8418272d385f.jpeg)
> ![DC86BAB3-E515-476B-B27B-96159A215327](https://user-images.githubusercontent.com/38060040/76167380-236a0100-61a1-11ea-80d3-e6396ef57a3c.jpeg)
> ![E2C3C7F6-EE81-4716-8CB7-9ABE0FE4A211](https://user-images.githubusercontent.com/38060040/76167381-24029780-61a1-11ea-805a-62a3a91335aa.jpeg)

https://github.com/hsxyhao/gridea-theme-next/issues/29#issue-577396256
参考这个issue的回答

**Comment by Mornwind** [comment]
> > 如下面三张图所示，可以看到，目录高亮比正文要晚1～2个标题。
> > ![C3C05C02-99FE-4C4B-B801-B414B65F7677](https://user-images.githubusercontent.com/38060040/76167377-21a03d80-61a1-11ea-9e76-8418272d385f.jpeg)
> > ![DC86BAB3-E515-476B-B27B-96159A215327](https://user-images.githubusercontent.com/38060040/76167380-236a0100-61a1-11ea-80d3-e6396ef57a3c.jpeg)
> > ![E2C3C7F6-EE81-4716-8CB7-9ABE0FE4A211](https://user-images.githubusercontent.com/38060040/76167381-24029780-61a1-11ea-805a-62a3a91335aa.jpeg)
> 
> [#29 (comment)](https://github.com/hsxyhao/gridea-theme-next/issues/29#issue-577396256)
> 参考这个issue的回答

原来如此。一开始我的markdown是有一级标题的，但是Gridea客户端强行要求把标题独立出来，我就只把一级标题移到标题栏去了，剩下的标题没有升一级。
