### ISSUE TITLE
切换到下载的最新主题后，本地渲染测试时报错

### ISSUE THREAD

**Issue by delphuy** [hsxyhao/gridea-theme-next#39]
今天下载的 (gridea-theme-next-master.zip )包，部署到指定目录后，本地渲染测试时报错。我本机环境如下：
Gridea版本：0.9.2 
OS：win10 专业版 1909 
报错如下：

![QQ截图20200326155103](https://user-images.githubusercontent.com/31920650/77623096-75b96900-6f7a-11ea-9b59-b6d10ad73556.jpg)

**Comment by hsxyhao** [comment]
> 今天下载的 (gridea-theme-next-master.zip )包，部署到指定目录后，本地渲染测试时报错。我本机环境如下：
> Gridea版本：0.9.2
> OS：win10 专业版 1909
> 报错如下：
> 
> ![QQ截图20200326155103](https://user-images.githubusercontent.com/31920650/77623096-75b96900-6f7a-11ea-9b59-b6d10ad73556.jpg)

可以切到友链配置项，开启自定义友链，保存一下，或者下载最新版，已修复

**Comment by delphuy** [comment]
已OK ，十分感谢！
