### ISSUE TITLE
希望取消掉目录部分的系统排序标号，容易与原有标题部分重复

### ISSUE THREAD

**Issue by qiaoxu123** [hsxyhao/gridea-theme-next#4]
![image](https://user-images.githubusercontent.com/25050767/71637319-c3278200-2c7a-11ea-893b-dcd020200c6b.png)

如图，1.1,1.2 的数字序号希望取消掉，个人建议

**Comment by hsxyhao** [comment]
> ![image](https://user-images.githubusercontent.com/25050767/71637319-c3278200-2c7a-11ea-893b-dcd020200c6b.png)
> 
> 如图，1.1,1.2 的数字序号希望取消掉，个人建议

一开始我也是没有添加自动排序的想法，但是每次写md的时候都要手动排序，感觉有点麻烦，所以就加上这个功能了，目前gridea的自定义主题配置还不是很完善，后期如果完善后，会对这块做自定义配置

**Comment by Jalr4ever** [comment]
> ![image](https://user-images.githubusercontent.com/25050767/71637319-c3278200-2c7a-11ea-893b-dcd020200c6b.png)
> 
> 如图，1.1,1.2 的数字序号希望取消掉，个人建议

这个好改啊，从该主题的目录依次找下去，然后找到这个函数：

![image](https://user-images.githubusercontent.com/23929139/71715710-51536200-2e4d-11ea-9c8d-d050e517ba58.png)

然后

`cur.text =  deep + ' ' + cur.text;` 改成 `cur.text =  ' ' + cur.text;` 即可
