### ISSUE TITLE
需求 新窗口打开链接及图片效果

### ISSUE THREAD

**Issue by o1f** [hsxyhao/gridea-theme-next#42]
文章内及友链 链接打开方式 _blank
文章图片能不能添加简易灯箱效果~
类似主题项目 https://github.com/qyxtim/bitcron-pro 
https://cdn.jsdelivr.net/gh/o1f/i/2020/03/29/Udos4fRO.gif

**Comment by hsxyhao** [comment]
> 文章内及友链 链接打开方式 _blank
> 文章图片能不能添加简易灯箱效果~
> 类似主题项目 https://github.com/qyxtim/bitcron-pro
> https://cdn.jsdelivr.net/gh/o1f/i/2020/03/29/Udos4fRO.gif
![image](https://user-images.githubusercontent.com/22101306/77854751-af120300-721e-11ea-906f-3573377f3d59.png)

友链的打开新窗口打开方式，我记得我我加过了，文章暂时还没有，其他两个先加todo里
