### ISSUE TITLE
再提一个bug，设定兼容封面后，若文章并没有设置封面，会显示一个图片占位符。

### ISSUE THREAD

**Issue by delphuy** [hsxyhao/gridea-theme-next#44]
如图：
封面策略选择的是 after；

![QQ截图20200401170720](https://user-images.githubusercontent.com/31920650/78119633-52d7fa80-743b-11ea-909f-32630e5a74d4.jpg)

**Comment by hsxyhao** [comment]
> 如图：
> 封面策略选择的是 after；
> 
> ![QQ截图20200401170720](https://user-images.githubusercontent.com/31920650/78119633-52d7fa80-743b-11ea-909f-32630e5a74d4.jpg)

这个设计的时候没有考虑到，当时想的就是选择了兼容肯定会上传封面的。我晚上修复一下
