### ISSUE TITLE
似乎开启兼容模式依然不能显示封面，封面为jsdelivr的

### ISSUE THREAD

**Issue by Aidanwangcy** [hsxyhao/gridea-theme-next#47]
如标题

**Comment by hsxyhao** [comment]
> 如标题
![image](https://user-images.githubusercontent.com/22101306/78421654-de47ca80-768b-11ea-9fea-9cf290254e7f.png)

gridea的文章列表有显示封面吗

**Comment by Aidanwangcy** [comment]
有的
<img width="986" alt="截屏2020-04-04 15 55 26" src="https://user-images.githubusercontent.com/29744854/78421769-db99a500-768c-11ea-962b-0a39ebf276ed.png">
这是gridea

![截屏2020-04-04 15 55 34](https://user-images.githubusercontent.com/29744854/78421772-df2d2c00-768c-11ea-91d8-aa308d4a4593.png)
这是网页

**Comment by Aidanwangcy** [comment]
是外链

**Comment by Aidanwangcy** [comment]
封面是外链

**Comment by Aidanwangcy** [comment]
> > 如标题
> > ![image](https://user-images.githubusercontent.com/22101306/78421654-de47ca80-768b-11ea-9fea-9cf290254e7f.png)
> 
> gridea的文章列表有显示封面吗

有的
这个是gridea的
<img width="986" alt="截屏2020-04-04 15 55 26" src="https://user-images.githubusercontent.com/29744854/78421866-b35e7600-768d-11ea-96d3-af0b9bd59e28.png">
这个是wang网页的
![截屏2020-04-04 15 55 34](https://user-images.githubusercontent.com/29744854/78421877-bce7de00-768d-11ea-90f6-fa1ad544e246.png)
封面是外链

**Comment by hsxyhao** [comment]
> > > 如标题
> > > ![image](https://user-images.githubusercontent.com/22101306/78421654-de47ca80-768b-11ea-9fea-9cf290254e7f.png)
> > 
> > 
> > gridea的文章列表有显示封面吗
> 
> 有的
> 这个是gridea的
> <img alt="截屏2020-04-04 15 55 26" width="986" src="https://user-images.githubusercontent.com/29744854/78421866-b35e7600-768d-11ea-96d3-af0b9bd59e28.png">
> 这个是wang网页的
> ![截屏2020-04-04 15 55 34](https://user-images.githubusercontent.com/29744854/78421877-bce7de00-768d-11ea-90f6-fa1ad544e246.png)
> 封面是外链

![image](https://user-images.githubusercontent.com/22101306/78422263-97100880-7690-11ea-99d5-641b03fd5d93.png)

这里的封面好像有了，但是加载失败了

**Comment by Aidanwangcy** [comment]
> ![image](https://user-images.githubusercontent.com/22101306/78422263-97100880-7690-11ea-99d5-641b03fd5d93.png)
> 
> 这里的封面好像有了，但是加载失败了

出现了这样的错误
![截屏2020-04-04 16 37 59](https://user-images.githubusercontent.com/29744854/78422581-db040d00-7692-11ea-94a8-65f1f838397d.png)

**Comment by hsxyhao** [comment]
> > ![image](https://user-images.githubusercontent.com/22101306/78422263-97100880-7690-11ea-99d5-641b03fd5d93.png)
> > 这里的封面好像有了，但是加载失败了
> 
> 出现了这样的错误
> ![截屏2020-04-04 16 37 59](https://user-images.githubusercontent.com/29744854/78422581-db040d00-7692-11ea-94a8-65f1f838397d.png)

好的，我明白了，我这边解决一下

**Comment by Aidanwangcy** [comment]
> 好的，我明白了，我这边解决一下

辛苦了非常感谢您
