### ISSUE TITLE
文章目录不能下滑

### ISSUE THREAD

**Issue by Linon419** [hsxyhao/gridea-theme-next#48]
当文章很长并且小标题很多时，左侧文章目录只能显示21个，并且不能下滑。比如这个<https://linon419.github.io/post/englishpod/>

**Comment by o1f** [comment]
哈哈哈,谁能想得到需要那么多目录 ..

等作者有空适配一下

**Comment by hsxyhao** [comment]
> 当文章很长并且小标题很多时，左侧文章目录只能显示21个，并且不能下滑。比如这个https://linon419.github.io/post/englishpod/

着实有点长，正在适配

**Comment by hsxyhao** [comment]
> 哈哈哈,谁能想得到需要那么多目录 ..
> 
> 等作者有空适配一下

确实啊，😃
