### ISSUE TITLE
归档，标签部分没有对应的图标

### ISSUE THREAD

**Issue by qiaoxu123** [hsxyhao/gridea-theme-next#5]
![image](https://user-images.githubusercontent.com/25050767/71637332-329d7180-2c7b-11ea-8aea-6687dc0495fc.png)

**Comment by hsxyhao** [comment]
首页、归档的标签看一下对应的link是不是默认的/以及/archives，菜单项gridea不支持icon，只能采取比较硬核的方案，只有当首页、归档以及标签页的连接分别为/、/archives、以及/tags才会出现标签
