### ISSUE TITLE
删除文章后同步到github仍然会在post/XXX下有文件

### ISSUE THREAD

**Issue by Cheny233** [hsxyhao/gridea-theme-next#50]
并且可以通过 名字.github.io/post/XXX访问
比如我已经删除了一个叫begin的文章
但github上仍然有
而且还能通过[cheny233.github.io/post/begin](https://cheny233.github.io/post/begin)访问

**Comment by hsxyhao** [comment]
> 并且可以通过 名字.github.io/post/XXX访问
> 比如我已经删除了一个叫begin的文章
> 但github上仍然有
> 而且还能通过[cheny233.github.io/post/begin](https://cheny233.github.io/post/begin)访问

这个貌似和主题的关系不是很大，可以去gridea的issue里面找一下
