### ISSUE TITLE
设置了背景音乐之后就无法保存配置了

### ISSUE THREAD

**Issue by Cheny233** [hsxyhao/gridea-theme-next#52]
修改：并不是背景音乐的原因
当重新修改基础配置后自定义配置就无法保存了

添加：修改友链部分内容后也会有这样的情况

**Comment by o1f** [comment]
我这边是设置图片的问题, 先把图片取消掉,比如说背景,个人联系设置的图片
然后修改你需要修改的地方
最后再添加图片 .

这个是 win 的bug ,等作者有时间找找原因.

**Comment by hsxyhao** [comment]
> 修改：并不是背景音乐的原因
> 当重新修改基础配置后自定义配置就无法保存了
> 
> 添加：修改友链部分内容后也会有这样的情况

参考楼下回复
