### ISSUE TITLE
代码背景问题

### ISSUE THREAD

**Issue by optimistic9527** [hsxyhao/gridea-theme-next#55]
![image](https://user-images.githubusercontent.com/37545032/79034831-983eb980-7beb-11ea-9cb5-ffafa7e410cc.png)
代码的主题调整了多次，但是背景颜色一直是白色，如何调整？
主背景调成黑色后拖动代码会变成图片的样子

**Comment by o1f** [comment]
代码高亮?

特性选项里面拉倒最下面,很多

也可以自己添加/替换 CSS

**Comment by hsxyhao** [comment]
> ![image](https://user-images.githubusercontent.com/37545032/79034831-983eb980-7beb-11ea-9cb5-ffafa7e410cc.png)
> 代码的主题调整了多次，但是背景颜色一直是白色，如何调整？
> 主背景调成黑色后拖动代码会变成图片的样子

代码块高亮那个之前的版本确实有问题，前天修复了一下，尝试下载最新版本，看看有没有问题

**Comment by optimistic9527** [comment]
@hsxyhao 高亮可以了，但是如果代码过长移动的时候还是会导致上面的问题

**Comment by hsxyhao** [comment]
> @hsxyhao 高亮可以了，但是如果代码过长移动的时候还是会导致上面的问题

嗯好，我晚上修复一下，可能上次修复漏了

**Comment by hsxyhao** [comment]
> > @hsxyhao 高亮可以了，但是如果代码过长移动的时候还是会导致上面的问题
> 
> 嗯好，我晚上修复一下，可能上次修复漏了

已修复

**Comment by optimistic9527** [comment]
@hsxyhao 感谢，已经修复
