### ISSUE TITLE
关于 设置图片之后无法保存的问题  以及临时解决办法

### ISSUE THREAD

**Issue by o1f** [hsxyhao/gridea-theme-next#56]
原因就应该是路径保存问题 .
下付临时解决办法:
就是把主题图片修改成外链或者相对路径
首先打开主题文件夹 ,打开`config.json` ,把 `picture-upload` 替换为`input `保存

![](https://cdn.jsdelivr.net/gh/o1f/i@master/2020/04/11/9mp8gkZV.png)

再打开就会发现图片不再是选中本地文件,而是输入方式

![](https://cdn.jsdelivr.net/gh/o1f/i@master/2020/04/11/1zqum1Qn.png)

可以选择外链,我这里填写的是随机图片API

录了两次效果图,结果gif太大了,

随机外链图效果预览 

![](https://cdn.jsdelivr.net/gh/o1f/i@master/2020/04/12/tL0JQIkx.gif)

https://cdn.jsdelivr.net/gh/o1f/i@master/2020/04/12/tL0JQIkx.gif

引用<https://api.ixiaowai.cn/>

## 本地文件

如果是本地的话

先把文件放入 主体文件夹`gridea-theme-next\assets\media\images`中

然后输入` /media/images/文件名`

例如:

![](https://cdn.jsdelivr.net/gh/o1f/i@master/2020/04/11/2U2OBqTR.gif)

https://cdn.jsdelivr.net/gh/o1f/i@master/2020/04/11/2U2OBqTR.gif

临时办法

等作者有空修改适配.

//////////////////////////////////////////////////////以下为原内容///////////////////////
--------
我这边打开开发者工具 ,设置的图片路径错误 ,

均为 file:///media/images/xxxxxx.jpg

而其他路径要么 file:f//绝对路径
或者 app,/ xx/ 相对路径 .

https://cdn.jsdelivr.net/gh/o1f/i@master/2020/04/11/rIjMn9gm.png

是路径错误的问题吗?

**Comment by hsxyhao** [comment]
> 我这边打开开发者工具 ,设置的图片路径错误 ,
> 
> 均为 file:///media/images/xxxxxx.jpg
> 
> 而其他路径要么 file:f//绝对路径
> 或者 app,/ xx/ 相对路径 .
> 
> https://cdn.jsdelivr.net/gh/o1f/i@master/2020/04/11/rIjMn9gm.png
> 
> 是路径错误的问题吗?

不太像，我这边mac还好，没什么错误，但是windows上就会出现类似你的错误

**Comment by o1f** [comment]
还有 音乐封面 和 社交图片也需要整一下 ~

**Comment by hsxyhao** [comment]
> 还有 音乐封面 和 社交图片也需要整一下 ~

抽时间弄下
