### ISSUE TITLE
avatar.png默认使用http访问

### ISSUE THREAD

**Issue by MiaoWu-T** [hsxyhao/gridea-theme-next#57]
如题，Chrome中按F12提示网站主体使用https，但/image/avatar.png使用了http（尽管单独访问/image/avatar.png时还是会自动跳转到https），看着地址栏旁边的不安全强迫症要犯了

不确定是不是主题的问题，到时候我再去Gridea那边提一个issue吧

**Comment by o1f** [comment]
开启强制https试试

**Comment by MiaoWu-T** [comment]
已经开了，cloudflare里面始终使用https，自动https改写，页面规则里把http自动跳转到https，甚至闲着没事干开了hsts（已经过验证了），都不行

**Comment by MiaoWu-T** [comment]
而且发现，直接复制头像图片链接得到的是https://miaowu-t.github.io/images/avatar.png，而chrome报错的链接是http://sangowen.xyz/images/avatar.png

**Comment by o1f** [comment]
我这边访问你的,默认是http,你要在CF设置 https 

https://cdn.jsdelivr.net/gh/o1f/i@master/2020/04/11/xyUNGCX7.png

**Comment by o1f** [comment]
看样子你是 域名解析设置问题了 .

**Comment by MiaoWu-T** [comment]
好吧，干脆我cf那边把域名删了重新来一遍好了

**Comment by MiaoWu-T** [comment]
谢谢大佬，解决了，之前的cname是在GitHub上设置的Custom domain，没加https，把原来的cname文件删掉再在gridea里面设置加上https就解决了👍

**Comment by o1f** [comment]
我只是一个小学生,谈不上大佬...

生活愉快.
