### ISSUE TITLE
一些疑问、问题以及建议

### ISSUE THREAD

**Issue by UserUnknownX** [hsxyhao/gridea-theme-next#58]
疑问(抱歉本人小白)：请问如何设置圆角图案(本人没有找到相关内容，给您添麻烦了)

问题：有时候友链界面的文字(头像下的)会消失。

建议：希望友链的格式能够修改一下，右边空着感觉挺奇怪的。

**Comment by hsxyhao** [comment]
> 疑问(抱歉本人小白)：请问如何设置圆角图案(本人没有找到相关内容，给您添麻烦了)
> 
> 问题：有时候友链界面的文字(头像下的)会消失。
> 
> 建议：希望友链的格式能够修改一下，右边空着感觉挺奇怪的。

1. 圆角图案如果是圆角效果的话，请看下图
![image](https://user-images.githubusercontent.com/22101306/79241561-c818e600-7ea5-11ea-953f-063cdaa610ae.png)

2. 头像下的文字会消失，暂时还不清楚，有类似的案例的话可以发一下，我看看

3. 右边空着应该是bug，我已经修复

**Comment by UserUnknownX** [comment]
> > 疑问(抱歉本人小白)：请问如何设置圆角图案(本人没有找到相关内容，给您添麻烦了)
> > 问题：有时候友链界面的文字(头像下的)会消失。
> > 建议：希望友链的格式能够修改一下，右边空着感觉挺奇怪的。
> 
> 1. 圆角图案如果是圆角效果的话，请看下图
>    ![image](https://user-images.githubusercontent.com/22101306/79241561-c818e600-7ea5-11ea-953f-063cdaa610ae.png)
> 2. 头像下的文字会消失，暂时还不清楚，有类似的案例的话可以发一下，我看看
> 3. 右边空着应该是bug，我已经修复

文字消失是有时保存后有延迟，后来看了源代码发现没有存上去，应该是因为显示的问题，打了字后不能立刻显示出来，好像需要等字全部显示后同步才能更新
