### ISSUE TITLE
手机无法正常显示

### ISSUE THREAD

**Issue by Cheny233** [hsxyhao/gridea-theme-next#59]
只能看到上面的黑框

**Comment by hsxyhao** [comment]
> 只能看到上面的黑框

描述信息太少了，最好能截张图，我方便排查问题

**Comment by o1f** [comment]
正常 啊 , 手机清缓存试试


![](https://developer-forum-online.cdn.bcebos.com/44976d3e-36db-4854-8fab-b04b358699c7.png)

**Comment by Cheny233** [comment]
ios的safari浏览器

**Comment by hsxyhao** [comment]
> 正常 啊 , 手机清缓存试试
> 也可能是网络不好.挂梯子
> 
> ![](https://camo.githubusercontent.com/d77595b83a31bcba17d232c02db1d047ad7a785d/68747470733a2f2f646576656c6f7065722d666f72756d2d6f6e6c696e652e63646e2e626365626f732e636f6d2f34343937366433652d333664622d343835342d386661622d6230346233353836393963372e706e67)

感觉可能和手机系统有关

**Comment by hsxyhao** [comment]
> ios的safari浏览器
> ![IMG_0369](https://user-images.githubusercontent.com/49137980/79629418-33033f00-817c-11ea-8fd6-58d4a39abcec.PNG)

我用我这边的safari打开，正常的
![image](https://user-images.githubusercontent.com/22101306/79629542-31864680-817d-11ea-8619-05d89cc03819.png)

**Comment by Cheny233** [comment]
那就奇怪了

**Comment by hsxyhao** [comment]
> 那就奇怪了

可以考虑换个浏览器或者手机测试一下
