### ISSUE TITLE
在Gridea客户端内添加封面图同步之后，网页上并没有对应的封面图

### ISSUE THREAD

**Issue by liuzhengjieis** [hsxyhao/gridea-theme-next#6]

**Comment by hsxyhao** [comment]
> _No description provided._

看下这个能不能帮助到你: [文章封面的问题](https://hsxyhao.github.io/post/shuo-yi-xia-next-zhu-ti/#%E6%96%87%E7%AB%A0%E5%B0%81%E9%9D%A2%E7%9A%84%E9%97%AE%E9%A2%98)
