### ISSUE TITLE
文章二级目录加载没问题，点击一级标题跳转后，需要向下滚动页面才会显示二级标题

### ISSUE THREAD

**Issue by setdiaoyong** [hsxyhao/gridea-theme-next#60]
文章目录显示，不是加载问题，我的想法是点击一级标题立即跳转，同时显示二级标题，我想先看目录，不知道是不是我设置目录压缩问题，向下滚动页面才会立即显示二级标题。

**Comment by o1f** [comment]
感觉还行啊,是不是动画原因 ? 我这边一般`1s`左右加载完成

![](https://file.5ewin.com/forum/20200418/a83aa5431de0de450b78186a0461ea8f.jpg)

**Comment by setdiaoyong** [comment]
估计是我搞了太多标题，一级标题11个，加上二级标题5个，可能是设置的问题，我在本地换着设置，测试中。试过多个内核的浏览器，突然想到，谷歌浏览器F12调试模式，看网页问题，有个报错，leancloud出问题了，估计没配置好，可能跟我这无法显示阅读数有关，我去看看
![报错](https://ftp.bmp.ovh/imgs/2020/04/70da3566bc36a427.png)

**Comment by setdiaoyong** [comment]
估计还跟上面黄色警告的图像加载缓慢有关，我自己看看去，先关了这个issue

**Comment by hsxyhao** [comment]
> 估计还跟上面黄色警告的图像加载缓慢有关，我自己看看去，先关了这个issue

你说的应该和这个配置有关系，可以了解下
![image](https://user-images.githubusercontent.com/22101306/79641579-00ccfe00-81cb-11ea-9da6-e4e87672b293.png)

**Comment by setdiaoyong** [comment]
谢谢，我不知道，在压缩的情况下，实现点击一级标题，文章跳转，但是不用向下滚动页面，目录能在点击一级标题后自动展示二级标题，是否有实现的需要，以及难度，只是我个人推荐。谢谢

**Comment by hsxyhao** [comment]
> 谢谢，我不知道，在压缩的情况下，实现点击一级标题，文章跳转，但是不用向下滚动页面，目录能在点击一级标题后自动展示二级标题，是否有实现的需要，以及难度，只是我个人推荐。谢谢

这个之前也有人提过，但是目前的话，实现起来，有些繁琐，暂时还不能把精力放在这个上面，可能后期会考虑怎么实现
