### ISSUE TITLE
界面显示修改：文章与站点概览的超链接文本、图标，是否可以分开设置颜色

### ISSUE THREAD

**Issue by setdiaoyong** [hsxyhao/gridea-theme-next#61]
![文章和站点概览超链接文本颜色同步](https://ftp.bmp.ovh/imgs/2020/04/2bdf7666759d0206.png)

### 感谢gridea和next主题，拯救了我

小白一个，之前搞了免费空间部署Typecho，感觉数据不在本地，不稳，果然，跪了两次。
虽然**gridea**暂时没有实时预览，但是可以先在**gridea**插图片，然后**VS code** 或**Atom**写文字，坐等**gridea**更新编辑器。

**Comment by hsxyhao** [comment]
> ![文章和站点概览超链接文本颜色同步](https://camo.githubusercontent.com/aafdbedff54b215bc1208e25628bcb82611d917e/68747470733a2f2f6674702e626d702e6f76682f696d67732f323032302f30342f326264663736363637353964303230362e706e67)
> 
> ### 感谢gridea和next主题，拯救了我
> 小白一个，之前搞了免费空间部署Typecho，感觉数据不在本地，不稳，果然，跪了两次。
> 虽然**gridea**暂时没有实时预览，但是可以先在**gridea**插图片，然后**VS code** 或**Atom**写文字，坐等**gridea**更新编辑器。

目前以上三部分本质都是超链接，主要是目前需要配置颜色的地方实在太多了，再增加的话，有些乱，可以考虑fork下，然后改动主题源码，还是比较简单的，有问题可以issue反馈

**Comment by setdiaoyong** [comment]
好的，谢谢，博客文章中写的网址，怎么设置成可以直接点击访问？

**Comment by hsxyhao** [comment]
> 好的，谢谢，博客文章中写的网址，怎么设置成可以直接点击访问？

是指md语法吗，[标题](http://www.xxx.com)这样？还是什么？

**Comment by setdiaoyong** [comment]
谢谢大佬，你这里写的标题是超链接文本，我的意思是直接在文章中写https://github.com在博客里也能识别成网址，成为超链接，可以点击跳转。如下图中3号是和你说的标题一样，1，2是我的意思，可以自动识别
![](https://ftp.bmp.ovh/imgs/2020/04/6f4bb97c6bbc6e47.png)

**Comment by o1f** [comment]
<链接地址>

**Comment by setdiaoyong** [comment]
嗯嗯，谢谢，还是因为我是md小白，得去学习一下
