### ISSUE TITLE
QAQ这是怎么了

### ISSUE THREAD

**Issue by hjxhjx-hub** [hsxyhao/gridea-theme-next#62]
为什么我的排版炸掉了

图片文字都乱七八糟的

求大佬帮助QAQ

**Comment by hsxyhao** [comment]
> 为什么我的排版炸掉了
> 
> 图片文字都乱七八糟的
> 
> 求大佬帮助QAQ

没有使用cdn的话，尝试切换一下风格，然后保存，本地预览看看能不能解决
![image](https://user-images.githubusercontent.com/22101306/79678767-576d2300-8231-11ea-8eff-ad8b75ec15b3.png)

**Comment by hjxhjx-hub** [comment]
为什么我的排版炸掉了

图片文字都乱七八糟的

求大佬帮助QAQ

没有使用cdn的话，尝试切换一下风格，然后保存，本地预览看看能不能解决
image



> > 为什么我的排版炸掉了
> > 图片文字都乱七八糟的
> > 求大佬帮助QAQ
> 
> 没有使用cdn的话，尝试切换一下风格，然后保存，本地预览看看能不能解决
> ![image](https://user-images.githubusercontent.com/22101306/79678767-576d2300-8231-11ea-8eff-ad8b75ec15b3.png)

真的好了诶，谢谢大佬qwq
