### ISSUE TITLE
小白把文件解压到themes了，但软件里没有这个主题的选项？

### ISSUE THREAD

**Issue by juju527** [hsxyhao/gridea-theme-next#63]
rt，求助

**Comment by hsxyhao** [comment]
> rt，求助

我估计是你放错文件夹了，你要放到站点源文件夹下
![image](https://user-images.githubusercontent.com/22101306/79681764-459a7880-824f-11ea-8fa8-a131fb64a9d6.png)

**Comment by juju527** [comment]
我是用的windows
![image](https://user-images.githubusercontent.com/63937641/79681832-ec7f1480-824f-11ea-8c56-cbeba80dda48.png)

**Comment by juju527** [comment]
哦，搞定了，谢谢你
