### ISSUE TITLE
0.4.0主题，点击预览后报错，在浏览器里点击博客主页文章标题，无法跳转

### ISSUE THREAD

**Issue by setdiaoyong** [hsxyhao/gridea-theme-next#70]
![](https://ftp.bmp.ovh/imgs/2020/04/5fd5e1a8869abc6f.png)
只要用0.3.0的title.ejs,替换就不报错

**Comment by o1f** [comment]
报错截图方便截图吗

**Comment by setdiaoyong** [comment]
![](https://ftp.bmp.ovh/imgs/2020/04/b1aded89816aefec.png)
报错是指的这个吗

**Comment by setdiaoyong** [comment]
只要把title.ejs换成上一个版本就不报错了

**Comment by hsxyhao** [comment]
> 只要把title.ejs换成上一个版本就不报错了

就是预览时gridea上报的错误信息

**Comment by hsxyhao** [comment]
> ![](https://camo.githubusercontent.com/99a6a39543703a52c8395d4a9c65a5ecf75a71b5/68747470733a2f2f6674702e626d702e6f76682f696d67732f323032302f30342f623161646564383938313661656665632e706e67)
> 报错是指在gridea中打开开发者工具报的错吗？

目前推测可能开启了url精简模式？此模式待兼容

**Comment by setdiaoyong** [comment]
> > ![](https://camo.githubusercontent.com/99a6a39543703a52c8395d4a9c65a5ecf75a71b5/68747470733a2f2f6674702e626d702e6f76682f696d67732f323032302f30342f623161646564383938313661656665632e706e67)
> > 报错是指在gridea中打开开发者工具报的错吗？
> 
> 目前推测可能开启了url精简模式？此模式待兼容

>@![hsxyhao](https://github.com/hsxyhao)我更新了，gridea开发者界面无报错，但是仍然有左边的报错，页面无法跳转，我再去试试不用url精简模式

**Comment by hsxyhao** [comment]
> > > ![](https://camo.githubusercontent.com/99a6a39543703a52c8395d4a9c65a5ecf75a71b5/68747470733a2f2f6674702e626d702e6f76682f696d67732f323032302f30342f623161646564383938313661656665632e706e67)
> > > 报错是指在gridea中打开开发者工具报的错吗？
> > 
> > 
> > 目前推测可能开启了url精简模式？此模式待兼容
> 
> > @![hsxyhao](https://github.com/hsxyhao)我更新了，gridea开发者界面无报错，但是仍然有左边的报错，页面无法跳转，我再去试试不用url精简模式

那文章的链接是自定义的吗？不是采用自带的/post/xxx这种？

**Comment by setdiaoyong** [comment]
![](https://ftp.bmp.ovh/imgs/2020/04/41217414fce633f6.png)
![](https://ftp.bmp.ovh/imgs/2020/04/c1c3b5ae33afaf5e.png)
测试了这样设置，虽然开发者工具报错，但是可以保证文章短命名，能跳转，而且文章访问量也可显示了，

**Comment by hsxyhao** [comment]
> ![](https://camo.githubusercontent.com/ac05c0b789675b53983a7c520a2188f15ed3f50c/68747470733a2f2f6674702e626d702e6f76682f696d67732f323032302f30342f343132313734313466636536333366362e706e67)
> ![](https://camo.githubusercontent.com/fcab5e34d3860da54cb8b0d8e11242d8f8d2adcc/68747470733a2f2f6674702e626d702e6f76682f696d67732f323032302f30342f633163336235616533336166616635652e706e67)
> 测试了这样设置，虽然开发者工具报错，但是可以保证文章短命名，能跳转，而且文章访问量也可显示了，

那个报错和主题没关系，暂时应该不影响了
