### ISSUE TITLE
文章目录问题

### ISSUE THREAD

**Issue by alpaca-brother** [hsxyhao/gridea-theme-next#74]
![Snipaste_2020-04-23_07-38-03](https://user-images.githubusercontent.com/50550449/80043848-64418d80-8535-11ea-8faf-38c5cf17882d.png)
![Snipaste_2020-04-23_07-37-36](https://user-images.githubusercontent.com/50550449/80043853-686dab00-8535-11ea-9299-4adc30e5fe96.png)
![Snipaste_2020-04-23_07-37-50](https://user-images.githubusercontent.com/50550449/80043857-6a376e80-8535-11ea-9cde-82193e6e6a0b.png)
![Snipaste_2020-04-23_07-37-10](https://user-images.githubusercontent.com/50550449/80043860-6c99c880-8535-11ea-9935-f2f681f2c4c2.png)
大佬，您的Next主题在我的站点[Alpaca Blog](https://alpaca-blog.xyz/)上出现了文章目录不显示/字体泛白的现象。
是我配置出错了吗？

**Comment by hsxyhao** [comment]
> ![Snipaste_2020-04-23_07-38-03](https://user-images.githubusercontent.com/50550449/80043848-64418d80-8535-11ea-8faf-38c5cf17882d.png)
> ![Snipaste_2020-04-23_07-37-36](https://user-images.githubusercontent.com/50550449/80043853-686dab00-8535-11ea-9299-4adc30e5fe96.png)
> ![Snipaste_2020-04-23_07-37-50](https://user-images.githubusercontent.com/50550449/80043857-6a376e80-8535-11ea-9cde-82193e6e6a0b.png)
> ![Snipaste_2020-04-23_07-37-10](https://user-images.githubusercontent.com/50550449/80043860-6c99c880-8535-11ea-9935-f2f681f2c4c2.png)
> 大佬，您的Next主题在我的站点[Alpaca Blog](https://alpaca-blog.xyz/)上出现了文章目录不显示/字体泛白的现象。
> 是我配置出错了吗？

是的配置有问题，目录的字体颜色在目录那个自定义配置那里
![image](https://user-images.githubusercontent.com/22101306/80044403-f39b7080-8536-11ea-8959-79c9452ca948.png)

**Comment by alpaca-brother** [comment]
好吧，原来配置选项在“自定义配置—目录”……
获得成就——“布莱茵德(blind)”……
![Snipaste_2020-04-23_07-49-55](https://user-images.githubusercontent.com/50550449/80044537-61479c80-8537-11ea-961b-2a63e375bacd.png)

**Comment by alpaca-brother** [comment]
顺带一提，大佬，您的主题对我这种小白而言非常友好，非常好用！
