### ISSUE TITLE
Pisces风格导航栏对不齐

### ISSUE THREAD

**Issue by H-olxx** [hsxyhao/gridea-theme-next#78]
![批注 2020-04-24 103133](https://user-images.githubusercontent.com/29517476/80169160-5106ee80-8617-11ea-8879-1a9937fa6741.png)

**Comment by hsxyhao** [comment]
可能是icon的问题，这个友链的icon太大了，后面换个小的就没有问题了

**Comment by H-olxx** [comment]
是“关于”的图标太小了，能不能在图标的<i>容器外面包一个控制宽度的块？

**Comment by hsxyhao** [comment]
> 是“关于”的图标太小了，能不能在图标的`<i>`容器外面包一个控制宽度的块？



> 是“关于”的图标太小了，能不能在图标的`<i>`容器外面包一个控制宽度的块？

加个宽度，居中一下，效果应该好点，可以体验下最新版
