### ISSUE TITLE
页内跳转能否不重置aplayer音乐

### ISSUE THREAD

**Issue by Cheny233** [hsxyhao/gridea-theme-next#80]

**Comment by Cheny233** [comment]
还有报错代码能不能不给红色，很难看
![20}5$I0@H K)BE8M{FE5 RN](https://user-images.githubusercontent.com/49137980/80195393-57fd2380-864e-11ea-95a7-2f2d06b8a1d3.png)

**Comment by hsxyhao** [comment]
> 还有报错代码能不能不给红色，很难看
> ![20}5$I0@H K)BE8M{FE5 RN](https://user-images.githubusercontent.com/49137980/80195393-57fd2380-864e-11ea-95a7-2f2d06b8a1d3.png)

1. 页面跳转播放器不停止，暂时还无法解决，后面可能会借用pjax，但是目前还有很多东西要修改，暂时只能先搁置。
2. 红色代码块系其他网友贡献代码，审核时没有仔细导致，目前已修复

**Comment by Cheny233** [comment]
> > 还有报错代码能不能不给红色，很难看
> > ![20}5$I0@H K)BE8M{FE5 RN](https://user-images.githubusercontent.com/49137980/80195393-57fd2380-864e-11ea-95a7-2f2d06b8a1d3.png)
> 
> 1. 页面跳转播放器不停止，暂时还无法解决，后面可能会借用pjax，但是目前还有很多东西要修改，暂时只能先搁置。
> 2. 红色代码块系其他网友贡献代码，审核时没有仔细导致，目前已修复

新的commit依然无法解决问题，代码块依然是红色的

**Comment by hsxyhao** [comment]
> > > 还有报错代码能不能不给红色，很难看
> > > ![20}5$I0@H K)BE8M{FE5 RN](https://user-images.githubusercontent.com/49137980/80195393-57fd2380-864e-11ea-95a7-2f2d06b8a1d3.png)
> > 
> > 
> > 
> > 1. 页面跳转播放器不停止，暂时还无法解决，后面可能会借用pjax，但是目前还有很多东西要修改，暂时只能先搁置。
> > 2. 红色代码块系其他网友贡献代码，审核时没有仔细导致，目前已修复
> 
> 新的commit依然无法解决问题，代码块依然是红色的

是不是cdn没有更新

**Comment by Cheny233** [comment]
是cdn的问题，只能等cdn刷新了

**Comment by hsxyhao** [comment]
> 是cdn的问题，只能等cdn刷新了，jsdelivr的缓存很久

发布个新版本强制更新，23333

**Comment by diego3893** [comment]
用Pjax呢



发自我的&nbsp;iPad


------------------ 原始邮件 ------------------
发件人: hsxyhao <notifications@github.com&gt;
发送时间: 2020年4月24日 17:42
收件人: hsxyhao/gridea-theme-next <gridea-theme-next@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[hsxyhao/gridea-theme-next] 页内跳转能否不重置aplayer音乐 (#80)





  
是cdn的问题，只能等cdn刷新了，jsdelivr的缓存很久
  
发布个新版本强制更新，23333
