### ISSUE TITLE
求助：请问新添加的菜单，如何更改前面默认的小图标

### ISSUE THREAD

**Issue by yangfanbit** [hsxyhao/gridea-theme-next#81]
RT，比如改成 fa-book 之类的。

**Comment by hsxyhao** [comment]
> RT，比如改成 fa-book 之类的。

![image](https://user-images.githubusercontent.com/22101306/80219229-c359ec00-8674-11ea-848a-4cf8e76104d4.png)
需要修改这里

**Comment by yangfanbit** [comment]
非常

> > RT，比如改成 fa-book 之类的。
> 
> ![image](https://user-images.githubusercontent.com/22101306/80219229-c359ec00-8674-11ea-848a-4cf8e76104d4.png)
> 需要修改这里

已修改，非常感谢~
