### ISSUE TITLE
请问：采用 jsdelivr cdn 加速 GitHub 资源后，更改内容页面宽度无效果？ 

### ISSUE THREAD

**Issue by yangfanbit** [hsxyhao/gridea-theme-next#83]
RT，去除cdn 预览有效果；同步后，也有。但若采用cdn，不论预览还是同步之后，宽度设置都还是原来的。配置文件删了重新同步还是没效果。

**Comment by o1f** [comment]
CDN有缓存的 , 发布新版本强制刷新

**Comment by yangfanbit** [comment]
> jsdelivr有缓存的 , 发布新版本强制刷新
> 把分支更改为版本号
> 示例
> https/链接xxxx/用户名/仓库名@master 更改为 @0.0.1

多谢~ 之前只填了 https/链接xxxx/用户名/仓库名 ，刚加个@master 预览就变了，这有什么区别吗？

**Comment by Cheny233** [comment]
> > jsdelivr有缓存的 , 发布新版本强制刷新
> > 把分支更改为版本号
> > 示例
> > https/链接xxxx/用户名/仓库名@master 更改为 @0.0.1
> 
> 多谢~ 之前只填了 https/链接xxxx/用户名/仓库名 ，刚加个@master 预览就变了，这有什么区别吗？

没什么区别，但是他们两个对应的是不同的缓存，jsdelivr的缓存更新要等很久才会更新

**Comment by yangfanbit** [comment]
> > > jsdelivr有缓存的 , 发布新版本强制刷新
> > > 把分支更改为版本号
> > > 示例
> > > https/链接xxxx/用户名/仓库名@master 更改为 @0.0.1
> > 
> > 
> > 多谢~ 之前只填了 https/链接xxxx/用户名/仓库名 ，刚加个@master 预览就变了，这有什么区别吗？
> 
> 没什么区别，但是他们两个对应的是不同的缓存，jsdelivr的缓存更新要等很久才会更新

明白了，谢谢！
