### ISSUE TITLE
移动设备加载速度远慢于电脑

### ISSUE THREAD

**Issue by Cheny233** [hsxyhao/gridea-theme-next#84]
如图，这是电脑的加载速度
![RQT3HXOET}@NTSO2)9R8N3F](https://user-images.githubusercontent.com/49137980/80274431-e2a45800-870c-11ea-8197-54b03523132b.png)

---
而这是移动设备的加载速度
![70}7(P(6O049V0E8ID}9YQ](https://user-images.githubusercontent.com/49137980/80274435-ee901a00-870c-11ea-8403-398844bdb5fd.png)

**Comment by o1f** [comment]
备案 , 国内服务器, CDN = 起飞 .

**Comment by hsxyhao** [comment]
> 如图，这是电脑的加载速度
> ![RQT3HXOET}@NTSO2)9R8N3F](https://user-images.githubusercontent.com/49137980/80274431-e2a45800-870c-11ea-8197-54b03523132b.png)
> 
> 而这是移动设备的加载速度
> ![70}7(P(6O049V0E8ID}9YQ](https://user-images.githubusercontent.com/49137980/80274435-ee901a00-870c-11ea-8403-398844bdb5fd.png)

![image](https://user-images.githubusercontent.com/22101306/80283975-0936b300-874e-11ea-8ba4-a1e848e7cf84.png)
![image](https://user-images.githubusercontent.com/22101306/80283980-12c01b00-874e-11ea-8e08-25b8deb1ae45.png)
感觉手机和电脑有点差距也可以理解，在电脑上开启移动端调试，测试的效果差不多
