### ISSUE TITLE
提个建议，音乐播放顺序逻辑建议

### ISSUE THREAD

**Issue by setdiaoyong** [hsxyhao/gridea-theme-next#85]
音乐播放，能不能不因为跳转页面而暂停播放，或者访问者打开音乐后，跳转不同页面播放不同音乐

**Comment by hsxyhao** [comment]
> 音乐播放，能不能不因为跳转页面而暂停播放，或者访问者打开音乐后，跳转不同页面播放不同音乐

后面考虑加一下pjax试试，可能效果会好一点
