### ISSUE TITLE
友链界面底部的留言格式部分

### ISSUE THREAD

**Issue by UserUnknownX** [hsxyhao/gridea-theme-next#87]
请问可以改为用户的名称、链接、子标题、头像吗？

虽然修改friends.ejs可以更改，不过每次更新都需要改有点麻烦

**Comment by hsxyhao** [comment]
> 请问可以改为用户的名称、链接、子标题、头像吗？
> 
> 虽然修改friends.ejs可以更改，不过每次更新都需要改有点麻烦

怎么改？具体描述下

**Comment by UserUnknownX** [comment]
> > 请问可以改为用户的名称、链接、子标题、头像吗？
> > 虽然修改friends.ejs可以更改，不过每次更新都需要改有点麻烦
> 
> 怎么改？具体描述下

![image](https://user-images.githubusercontent.com/50655871/80449512-e8d74600-8951-11ea-8e51-6a887983d687.png)

如改为

![image](https://user-images.githubusercontent.com/50655871/80449705-63a06100-8952-11ea-99af-075789b07fc5.png)

**Comment by UserUnknownX** [comment]
顺便问一下，介绍多行写法是要如何使用\n

需要转义或者用引号吗？

**Comment by o1f** [comment]
建议使用git命令更新 . 一般不会覆盖本地修改

**Comment by hsxyhao** [comment]
> 顺便问一下，介绍多行写法是要如何使用\n
> 
> 需要转义或者用引号吗？

\n暂时不支持转义，不太明白，为什么需要转义

**Comment by UserUnknownX** [comment]
> > 顺便问一下，介绍多行写法是要如何使用\n
> > 需要转义或者用引号吗？
> 
> \n暂时不支持转义，不太明白，为什么需要转义

好像我打\n没法换行（不太知道具体操作）

本来认为是需要//转为\

请问一下例如

```
A
B
```

应该怎么打呢

**Comment by o1f** [comment]
a\nb

**Comment by UserUnknownX** [comment]
> a\nb
> 
> ![](https://camo.githubusercontent.com/a21e029cf988c8166e684db77180e16114bb0100/68747470733a2f2f7570696d6167652e616c6578686368752e636f6d2f323032302f30342f32382f383464616433663464653265382e706e67)

谢谢，发现忘记重启gridea了😂

**Comment by hsxyhao** [comment]
> > > 请问可以改为用户的名称、链接、子标题、头像吗？
> > > 虽然修改friends.ejs可以更改，不过每次更新都需要改有点麻烦
> > 
> > 
> > 怎么改？具体描述下
> 
> ![image](https://user-images.githubusercontent.com/50655871/80449512-e8d74600-8951-11ea-8e51-6a887983d687.png)
> 
> 如改为
> 
> ![image](https://user-images.githubusercontent.com/50655871/80449705-63a06100-8952-11ea-99af-075789b07fc5.png)

下次这种情况的，我觉得可以提交pull request，参与开源岂不乐哉^^，快乐满满

**Comment by UserUnknownX** [comment]
> > > > 请问可以改为用户的名称、链接、子标题、头像吗？
> > > > 虽然修改friends.ejs可以更改，不过每次更新都需要改有点麻烦
> > > 
> > > 
> > > 怎么改？具体描述下
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/50655871/80449512-e8d74600-8951-11ea-8e51-6a887983d687.png)
> > 如改为
> > ![image](https://user-images.githubusercontent.com/50655871/80449705-63a06100-8952-11ea-99af-075789b07fc5.png)
> 
> 下次这种情况的，我觉得可以提交pull request，参与开源岂不乐哉^^，快乐满满

好的QwQ

**Comment by UserUnknownX** [comment]
> > > > 请问可以改为用户的名称、链接、子标题、头像吗？
> > > > 虽然修改friends.ejs可以更改，不过每次更新都需要改有点麻烦
> > > 
> > > 
> > > 怎么改？具体描述下
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/50655871/80449512-e8d74600-8951-11ea-8e51-6a887983d687.png)
> > 如改为
> > ![image](https://user-images.githubusercontent.com/50655871/80449705-63a06100-8952-11ea-99af-075789b07fc5.png)
> 
> 下次这种情况的，我觉得可以提交pull request，参与开源岂不乐哉^^，快乐满满

好的QwQ
