### ISSUE TITLE
主题做出来的包越来越大

### ISSUE THREAD

**Issue by Cheny233** [hsxyhao/gridea-theme-next#88]
主体做出来的包越来越大，导致同步也变慢，仔细看了一下，主要大小在live2d这个文件夹里，为什么突然变大了这么多？

**Comment by Cheny233** [comment]
而且我更担心的是如果以后大于50m后就用不了jsdelivr

**Comment by hsxyhao** [comment]
> 主体做出来的包越来越大，导致同步也变慢，仔细看了一下，主要大小在live2d这个文件夹里，为什么突然变大了这么多？

看板娘加的多了，后面准备把看板娘弄成手动安装的方式，还有一个就是git的文件也越来越大，我晚上优化下

**Comment by diego3893** [comment]
看板娘可以手动，也可以直接用网上cdn的live2d控件最好



发自我的&nbsp;iPad


------------------ 原始邮件 ------------------
发件人: hsxyhao <notifications@github.com&gt;
发送时间: 2020年4月27日 21:41
收件人: hsxyhao/gridea-theme-next <gridea-theme-next@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[hsxyhao/gridea-theme-next] 主题做出来的包越来越大 (#88)





  
主体做出来的包越来越大，导致同步也变慢，仔细看了一下，主要大小在live2d这个文件夹里，为什么突然变大了这么多？
  
看板娘加的多了，后面准备把看板娘弄成手动安装的方式，还有一个就是git的文件也越来越大，我晚上优化下

**Comment by hsxyhao** [comment]
> 看板娘可以手动，也可以直接用网上cdn的live2d控件最好 发自我的&nbsp;iPad
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: hsxyhao <notifications@github.com&gt; 发送时间: 2020年4月27日 21:41 收件人: hsxyhao/gridea-theme-next <gridea-theme-next@noreply.github.com&gt; 抄送: Subscribed <subscribed@noreply.github.com&gt; 主题: 回复：[hsxyhao/gridea-theme-next] 主题做出来的包越来越大 (#88) 主体做出来的包越来越大，导致同步也变慢，仔细看了一下，主要大小在live2d这个文件夹里，为什么突然变大了这么多？ 看板娘加的多了，后面准备把看板娘弄成手动安装的方式，还有一个就是git的文件也越来越大，我晚上优化下 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

是的，之前没有注意到，等我加进去之后就发现这个问题了，但是当时已经改完了，就有些麻烦了，想想还是先发布，今晚抽时间解决下
