### ISSUE TITLE
搜索奇奇怪怪地无法使用

### ISSUE THREAD

**Issue by UserUnknownX** [hsxyhao/gridea-theme-next#97]
[RT](https://userunknownx.github.io/)

是需要是什么配置吗QwQ

**Comment by o1f** [comment]
放个地址

**Comment by UserUnknownX** [comment]
> 放个地址

地址就是RT那里https://userunknownx.github.io/

>_<

**Comment by o1f** [comment]
https://upimage.alexhchu.com/2020/05/08/edc99e0083b48.png

检查一下 ,好像有个空格

**Comment by UserUnknownX** [comment]
> https://upimage.alexhchu.com/2020/05/08/edc99e0083b48.png
> 
> 检查一下 ,好像有个空格

谢谢，去掉cdn就好了QaQ（不过没有打上那个空格，有点奇怪

**Comment by o1f** [comment]
主题问题,多了个空格,我这边提交下pr

**Comment by UserUnknownX** [comment]
> https://upimage.alexhchu.com/2020/05/08/edc99e0083b48.png
> 
> 检查一下 ,好像有个空格



> 主题问题,多了个空格,我这边提交下pr

您可以顺便把搜索大小写PR一下吗QwQ(好像搜索区分大小写

**Comment by o1f** [comment]
我不会啊~

**Comment by UserUnknownX** [comment]
> 我不会啊~

我也不会，，，
